---
title: "MSE testing"
author: "Grant Adams"
format: pptx
editor: visual
---

## Fitting OMs

```{r, echo = TRUE, eval = TRUE}
library(Rceattle)
data("NorthernRockfish2022")
nrdata <- NorthernRockfish2022
nrdata$fleet_control$proj_F_prop <- 1

om <- Rceattle::fit_mod(
  data_list = nrdata,
  estimateMode = 0,  # Estimate
  initMode = 1,      # Assume unfished equilibrium
  phase = TRUE,
  M1Fun = build_M1(
    updateM1 = TRUE,
    M1_model = 1,
    M1_use_prior = TRUE,
    M_prior = 0.06,
    M_prior_sd = 0.05)
)
```

----

## Fitting EMs (Tier 3 HCR)

```{r, echo = TRUE, eval = TRUE}
em <- Rceattle::fit_mod(
  data_list = nrdata,
  estimateMode = 0, # Estimate
  verbose = 1,
  phase = TRUE,
  initMode = 1,      # Assume unfished equilibrium
  M1Fun = build_M1(
    updateM1 = TRUE,
    M1_model = 1,
    M1_use_prior = TRUE,
    M_prior = 0.06,
    M_prior_sd = 0.05),
  HCR = build_hcr(HCR = 5,       # Tier3 HCR
                  Ftarget = 0.4, # F40%
                  Flimit = 0.35, # F35%
                  Plimit = 0.2,  # No fishing when SB<SB20
                  Alpha = 0.05)
)
```

----

## Running MSEs

```{r, echo = TRUE, eval = TRUE}
mse1 <- run_mse(
  om = om, em = em, 
  nsim = 10, 
  assessment_period = 2,
  sampling_period = c(1, 2) # Fishery = fleet 1, BTS = fleet 2
)
```

----

## Evaluating MSEs via plots

```{r, echo = TRUE, eval = TRUE}
plot_depletionSSB(lapply(mse1, function(x) x$OM))
```

```{r, echo = TRUE, eval = TRUE}
plot_depletionSSB(
  c(mse1$Sim_1$EM,           # EMs
    list(mse1$Sim_1$OM,      # OM
         mse1$Sim_1$OM_no_F  # OM w/ no fishing
    )),    
  line_col = c(
    paste0("grey", round(seq(80, 50, length.out = 15))),
    1, 3
  )
)
```

----

## Summary statistics

```{r, echo = TRUE, eval = TRUE}
library(kableExtra)
mse_summ <- mse_summary(mse1)
kable(mse_summ, digits = 2)
```

----

# Alternative scenarios

----

## Different BRPs

```{r, echo = TRUE, eval = TRUE}
em2 <- Rceattle::fit_mod(
  data_list = nrdata,
  estimateMode = 0, # Estimate
  verbose = 1,
  phase = TRUE,
  initMode = 1,      # Assume unfished equilibrium
  M1Fun = build_M1(
    updateM1 = TRUE,
    M1_model = 1,
    M1_use_prior = TRUE,
    M_prior = 0.06,
    M_prior_sd = 0.05),
  HCR = build_hcr(HCR = 5,       # Tier3 HCR
                  Ftarget = 0.30,# F40%
                  Flimit = 0.10, # F35%
                  Plimit = 0,    # No limit
                  Alpha = 0.1)
)
```

----

## MSE 2

```{r, echo = TRUE, eval = TRUE}
mse2 <- run_mse(
  om = om, em = em2, 
  nsim = 10, 
  assessment_period = 2,
  sampling_period = c(1, 2) # Fishery = fleet 1, BTS = fleet 2
)
```

----

## Triannual BTS

```{r, echo = TRUE, eval = TRUE}
mse3 <- run_mse(
  om = om, em = em, 
  nsim = 10, 
  assessment_period = 2,
  sampling_period = c(1, 3) # Fishery = fleet 1, BTS = fleet 2
)
```

----

## 4-year cycle and 50% sampling

```{r, echo = TRUE, eval = TRUE}
mse4 <- run_mse(
  om = om, em = em, 
  nsim = 10, 
  fut_sample = 0.5,
  assessment_period = 4,
  sampling_period = c(1, 2) # Fishery = fleet 1, BTS = fleet 2
)
```

----

## Climate resilience

```{r, echo = TRUE, eval = TRUE}
nrdata$env_data <- data.frame(
  Year = nrdata$styr:nrdata$projyr,
  Index = 1:90 * 0.5 + rnorm(90))

om2 <- Rceattle::fit_mod(
  data_list = nrdata,
  estimateMode = 0,  # Estimate
  initMode = 1,      # Assume unfished equilibrium
  phase = TRUE,
  M1Fun = build_M1(
    updateM1 = TRUE,
    M1_model = 1,
    M1_use_prior = TRUE,
    M_prior = 0.06,
    M_prior_sd = 0.05),
  recFun = build_srr(
    srr_fun = 1,    # Mean R with covariates
    srr_indices = 1),
)

plot_biomass(om2, incl_proj = TRUE)
```

## MSE 5

```{r, echo = TRUE, eval = TRUE}
mse5 <- run_mse(
  om = om2, em = em, 
  nsim = 10, 
  fut_sample = 0.5,
  assessment_period = 4,
  sampling_period = c(1, 2) # Fishery = fleet 1, BTS = fleet 2
)
```

----

# Overall summary

```{r, echo = TRUE, eval = TRUE}
mse_summ$MSE = 1
mse_summ2 <- mse_summary(mse2); mse_summ2$MSE = 2
mse_summ3 <- mse_summary(mse3); mse_summ3$MSE = 2
mse_summ4 <- mse_summary(mse4); mse_summ4$MSE = 2

kable(do.call("rbind", list(mse_summ, mse_summ2, mse_summ3, mse_summ4)) %>%
        dplyr::relocate(MSE), digits = 2)
```
