---
title: "Rceattle"
author: "Grant Adams"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ceattle_bibliography.bib
---

CEATTLE is short for Climate-Enhanced, Age-based model with Temperature-specific Trophic Linkages and Energetics, which is a multi-species age-structured assessment model developed for groundfish in the Bering Sea, USA by Holsman et al. [-@Holsman2015]. To incorporate the impacts of climate, the model includes temperature-dependent von Bertalanffy weight-at-age functions (VBGF) and temperature-specific, bioenergetics-based predation interactions. Inputs of the model include U.S. National Marine Fisheries Service Alaska Fisheries Science Center (AFSC) survey and fishery data. Outputs include historical estimates of predation mortality, fishing mortality, biomass, recruitment, etc.

`Rceattle` is an `R` package designed to implement the CEATTLE model using Template Model Builder (`TMB`; @Kristensen2015), which can be installed using following https://github.com/kaskr/adcomp/wiki/Download. Rceattle is structured similar to the original manuscript in terms of modularization. Seperate functions (i.e. modules) estimate retrospective temperature- and size-specific predator rations, prey preference, and weight-at- age. These are then used as inputs to the CEATTLE model to evaluate how predation mortality, recruitment, and survival of three target species change under historical climate conditions and harvest rates.

Currently `RCeattle` can take CEATTLE ADMB based inputs and estimates them in `TMB`. To run `Rceattle` a user can either load a data set or build a data set from ADMB dat files by selecting a control file located in a data directory with `.dat` files used in ADMB and using the `build_dat` function. The model will then initialize assuming $0$ for all parameters unless a parameter list is provided or `"ceattle.par"` or `"ceattle_par.std"` is selected. In the later case, a .par or .std file provided from a previously estimated ADMB model can be used and specified with associated directory (i.e. `"mydir/ceattle_par.std"`). Documentation for all functions can be found using `?`.

# Install `Rceattle`:
```{R eval = FALSE}
install.packages("mydir/Rceattle_0.0.0.9000.tar.gz", type="source")
```

# Example
For example, to run the 2017 single species assessment for the Bering Sea, a data file must first be loaded:
```{R eval = FALSE}
library(Rceattle)
data(BS2017SS) # ?BS2017SS for more information on the data
```
Then the model can be fit by setting `msmMode = 0` using the `Rceattle` function:
```{R eval = FALSE}
ss_run <- Rceattle::fit_mod(data_list = BS2017SS,
                   inits = NULL, # Initial parameters = 0
                   file_name = NULL, # Don't save
                   debug = 0, # Estimate
                   random_rec = FALSE, # No random recruitment
                   msmMode = 0, # Single species mode
                   silent = TRUE)
```
The you can plot the model results using using
```{R eval = FALSE}
plot_biomass(Rceattle =  ss_run)
plot_recruitment(Rceattle =  ss_run)
```


For the 2017 multispecies model starting from the single species parameters, the following can be specified:
```{R eval = FALSE}
data("BS2017MS")
ms_run <- Rceattle::fit_mod(data_list = BS2017MS,
                   inits = ss_run$estimated_params, # Initial parameters from single species ests
                   file_name = NULL, # Don't save
                   debug = 0, # Estimate
                   niter = 10, # 10 iterations around population and predation dynamics
                   random_rec = FALSE, # No random recruitment
                   msmMode = 1, # MSVPA based
                   suitMode = 0, # empirical suitability
                   silent = TRUE)
```

We can plot both runs as well:
```{R eval = FALSE}
mod_list <- list(ss_run, ms_run)
mod_names <- c("SS", "MS")

# Plot biomass trajectory
plot_biomass(Rceattle = mod_list, model_names = mod_names)
plot_recruitment(Rceattle = mod_list, model_names = mod_names)

plot_selectivity(Rceattle = mod_list, model_names = mod_names)
plot_mort(Rceattle = mod_list, model_names = mod_names, age = 2)
```

Data can be simulated from the estimated quantities using `sim_mod`:
```{R eval = FALSE}
ss_sim <- sim_mod(ss_run)

ss_sim_run <- Rceattle::fit_mod(
  data_list = ss_sim,
  inits = NULL, # Initial parameters = 0
  file_name = NULL, # Don't save
  debug = 0, # Estimate
  random_rec = FALSE, # No random recruitment
  msmMode = 0, # Single species mode
  silent = TRUE)

# Simulate the multispecies model
ms_sim <- sim_mod(ms_run)

ms_sim_run <- Rceattle::fit_mod(
  data_list = ms_sim,
  inits = ss_run$estimated_params, # Initial parameters = 0
  file_name = NULL, # Don't save
  debug = 0, # Estimate
  random_rec = FALSE, # No random recruitment
  msmMode = 1, # Holsman MS mode
  silent = TRUE)

# We can plot the simulated runs
mod_list <- list(ss_sim_run, ms_sim_run)
mod_names <- c("SS sim", "MS sim")

plot_biomass(Rceattle = mod_list, model_names = mod_names)
plot_recruitment(Rceattle = mod_list, model_names = mod_names)
```


For recruitment, the model assumes that recruitment $R$ of species $sp$ follows the following equation:
$$R_{sp,yr} = R0_{sp} * e^{Rdev_{sp, yr}}$$
$$Rdev_{sp, yr} \sim N(0, \sigma_{r,sp})$$
Following Holsman et al. [-@Holsman2015], $\sigma_{r,sp}$ can be fixed at `sqrt(0.5)` and the model estimated using penalized likelihood, by setting `ranfom_rec = FALSE`. Alternatively, `Rdev` can be treated as random effects and $\sigma_{r,sp}$ estimated by setting `random_rec = TRUE`:
```{R eval = FALSE}
ss_re <- Rceattle::fit_mod(
  data_list = BS2017SS,
  inits = NULL, # Initial parameters = 0
  file_name = NULL, # Don't save
  debug = 0, # Estimate
  random_rec = TRUE, # Turn of recruitment deviations as random effects
  msmMode = 0, # Single species mode
  silent = TRUE)
```

# References


