---
title: "Rceattle"
author: "Grant Adams, Kirstin Holsman"
date: "8/2/2018"
output:
  pdf_document: default
  word_document: default
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/dependent/fisheries-research.csl
bibliography: ceattle_bibliography.bib
vignette: |
  %\VignetteIndexEntry{CEATTLE Walkthrough} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
---

CEATTLE is short for Climate-Enhanced, Age-based model with Temperature-specific Trophic Linkages and Energetics, which is a multi-species age-structured assessment model developed for groundfish in the Bering Sea, USA by Holsman et al. [-@Holsman2015]. To incorporate the impacts of climate, the model includes temperature-dependent von Bertalanffy weight-at-age functions (VBGF) and temperature-specific, bioenergetics-based predation interactions. Inputs of the model include U.S. National Marine Fisheries Service Alaska Fisheries Science Center (AFSC) survey and fishery data. Outputs include historical estimates of predation mortality, fishing mortality, biomass, recruitment, etc.

`Rceattle` is an `R` package designed to implement the CEATTLE model using Template Model Builder (`TMB`; @Kristensen2015). Rceattle is structured similar to the original manuscript in terms of modularization. Seperate functions (i.e. modules) estimate retrospective temperature- and size-specific predator rations, prey preference, and weight-at- age. These are then used as inputs to the CEATTLE model to evaluate how predation mortality, recruitment, and survival of three target species change under historical climate conditions and harvest rates. Estimates from CEATTLE in `Rceattle` can then be forward projected to derive estimates of unfished biomass and fishing mortality under future climate conditions and various harvest scenarios.

Currently `RCeattle` takes CEATTLE ADMB based inputs and estimates them in `TMB`. To run `Rceattle` a user selects a control file located in a data directory with `.dat` files used in ADMB. The model will then initialize assuming $0$ for all parameters unless a parameter list is provided or `"ceattle.par"` or `"ceattle_par.std"` is selected. In the later case, a .par or .std file provided from a previously estimated ADMB model must by included in the folder prior to the data directory. Currently, .dat files and ADMB outputs are included in the `\data` folder.

# Example
For example, to run the 2017 single species assessment for the Bering Sea, a data file must first be created:
```{R eval=FALSE}
data_list_ss <- build_dat(ctlFilename = "asmnt2017_0A_corrected", TMBfilename = "ceattle_v01_02", dat_dir = "data/BSAI/BS_SS_Files/dat files/", nspp = 3)
```
Then the model can be fit by setting `msmMode = 0` using the `Rceattle` function:
```{R eval=FALSE}
ss_run <- Rceattle(TMBfilename = "ceattle_v01_02", 
                   data_list = data_list_ss,
                   inits = NULL, # Initial parameters = 0
                   file_name = NULL, # Don't save
                   debug = 0, # Estimate
                   random_rec = FALSE, # No random recruitment
                   msmMode = 0, # Single species mode
                   avgnMode = 0,
                   silent = FALSE)
```
The you can plot the model results using using
```{R eval=FALSE}
plot_biomass(ceattle_list =  list(ss_run))
plot_recruitment(ceattle_list =  list(ss_run))
```


For the 2017 multispecies model starting from the single species parameters, the following can be specified:
```{R eval=FALSE}
data_list_ms <- build_dat(ctlFilename = "asmnt2017_2A_corrected", TMBfilename = "ceattle_v01_02", dat_dir = "data/BSAI/BS_MS_Files/dat files/", nspp = 3)

ms_run <- Rceattle(TMBfilename = "ceattle_v01_02", 
                   data_list = data_list_ms,
                   inits = ss_run$estimated_params, # Initial parameters from ss run
                   file_name = NULL, # Don't save
                   debug = 1, # Estimate
                   random_rec = FALSE, # No random recruitment
                   niter = 10, # Number of iterations around predation/pop dy functions
                   msmMode = 1, # Multi-species holsman mode
                   avgnMode = 0)

plot_biomass(ceattle_list =  list(ms_run))
plot_recruitment(ceattle_list =  list(ms_run))
```

We can plot both runs as well:
```{R eval=FALSE}
plot_biomass(ceattle_list =  list(ms_run, ss_run), model_names = c("MS", "SS"))
plot_recruitment(ceattle_list =  list(ms_run, ss_run), model_names = c("MS", "SS"))
```

Data can be simulated from the estimated quantities using `sim_mod`:
```{R eval = FALSE}
ss_sim <- sim_mod(ss_run)

ss_sim_run <- Rceattle(TMBfilename = "ceattle_v01_02", 
                   data_list = ss_sim,
                   inits = NULL, # Initial parameters = 0
                   file_name = NULL, # Don't save
                   debug = 0, # Estimate
                   random_rec = FALSE, # No random recruitment
                   msmMode = 0, # Single species mode
                   avgnMode = 0,
                   silent = FALSE)

ms_sim <- sim_mod(ms_run)

ms_sim_run <- Rceattle(TMBfilename = "ceattle_v01_02", 
                   data_list = ms_sim,
                   inits = NULL, # Initial parameters = 0
                   file_name = NULL, # Don't save
                   debug = 0, # Estimate
                   random_rec = FALSE, # No random recruitment
                   msmMode = 1, # Holsman MS mode
                   avgnMode = 0,
                   silent = FALSE)


```


For recruitment, the model assumes that recruitment $R$ of species $sp$ follows the folloiwng equation:
$$R_{sp,yr} = R0_{sp} * e^{Rdev_{sp, yr}}$$
$$Rdev_{sp, yr} \sim N(0, \sigma_{r,sp})$$
Following Holsman et al. [-@Holsman2015], $\sigma_{r,sp}$ can be fixed at `sqrt(0.05)` and the model estimated using penalized likelihood, by setting `ranfom_rec = FALSE`. Alternatively, `Rdev` can be treated as random effects and $\sigma_{r,sp}$ estimated by setting `random_rec = TRUE`:
```{R eval = FALSE}
ss_re <- Rceattle(TMBfilename = "ceattle_v01_02", 
                   data_list = ss_sim,
                   inits = NULL, # Initial parameters = 0
                   file_name = NULL, # Don't save
                   debug = 0, # Estimate
                   random_rec = TRUE, # No random recruitment
                   msmMode = 0, # Single species mode
                   avgnMode = 0,
                   silent = FALSE)
```

# References
