# The six timeseries plot_* wrappers are generated by .ts_wrapper(). Plot output
# is not covered by golden-check, so these guard that each wrapper still pins the
# right derived series (output) and y-axis label and forwards its arguments to
# plot_timeseries() unchanged.

test_that("plot_* timeseries wrappers forward the pinned output/ylab and pass args through", {
  captured <- NULL
  testthat::local_mocked_bindings(
    plot_timeseries = function(Rceattle, output, ylab, ...) {
      captured <<- c(list(output = output, ylab = ylab), list(...))
      invisible(NULL)
    }
  )

  expected <- list(
    plot_biomass             = c("biomass",             "Age-1+ biomass (million mt)"),
    plot_recruitment         = c("R",                   "Age-1 recruits (million)"),
    plot_ssb                 = c("ssb",                 "Age-1+ ssb (million mt)"),
    plot_exploitable_biomass = c("exploitable_biomass", "Max exploitable biomass (million mt)"),
    plot_depletionSSB        = c("ssb_depletion",       "SSB depletion"),
    plot_depletion           = c("biomass_depletion",   "Biomass depletion"),
    plot_ssb_depletion       = c("ssb_depletion",       "SSB depletion") # deprecated alias
  )

  for (fn in names(expected)) {
    captured <- NULL
    get(fn, envir = asNamespace("Rceattle"))("dummy_model", add_ci = TRUE, lwd = 5)
    expect_identical(captured$output, expected[[fn]][1], info = fn)
    expect_identical(captured$ylab,   expected[[fn]][2], info = fn)
    # pass-through arguments survive unchanged
    expect_identical(captured$add_ci, TRUE, info = fn)
    expect_identical(captured$lwd,    5,    info = fn)
  }
})

test_that("generated wrappers keep the documented public argument list", {
  # The wrappers pin output/ylab but must otherwise expose the exact signature
  # users depend on (partial-arg matching, introspection). Guard it explicitly.
  api_args <- c("Rceattle", "file", "model_names", "line_col", "species",
                "spnames", "add_ci", "lwd", "save", "right_adj", "legend.pos",
                "width", "height", "minyr", "maxyr", "incl_proj", "mod_cex",
                "lty", "alpha", "mod_avg", "mse", "OM", "reference")
  for (fn in c("plot_biomass", "plot_recruitment", "plot_ssb",
               "plot_exploitable_biomass", "plot_depletionSSB", "plot_depletion")) {
    expect_identical(names(formals(get(fn, envir = asNamespace("Rceattle")))),
                     api_args, info = fn)
  }
})
