# The six timeseries plot_* wrappers are generated by .ts_wrapper(). Plot output
# is not covered by golden-check, so these guard that each wrapper still pins the
# right derived series (output) and forwards its arguments to plot_timeseries()
# unchanged. The y-axis label is no longer pinned by the wrapper -- it is derived
# in plot_timeseries() from the series and the model's minage -- so it is tested
# separately against .rce_ts_ylab() below.

test_that("plot_* timeseries wrappers forward the pinned output and pass args through", {
  captured <- NULL
  testthat::local_mocked_bindings(
    plot_timeseries = function(Rceattle, output, ylab, ...) {
      captured <<- c(list(output = output, ylab = ylab), list(...))
      invisible(NULL)
    }
  )

  expected <- list(
    plot_biomass             = "biomass",
    plot_recruitment         = "R",
    plot_ssb                 = "ssb",
    plot_exploitable_biomass = "exploitable_biomass",
    plot_depletionSSB        = "ssb_depletion",
    plot_depletion           = "biomass_depletion",
    plot_ssb_depletion       = "ssb_depletion" # deprecated alias
  )

  for (fn in names(expected)) {
    captured <- NULL
    get(fn, envir = asNamespace("Rceattle"))("dummy_model", add_ci = TRUE, lwd = 5)
    expect_identical(captured$output, expected[[fn]], info = fn)
    # ylab is left NULL so plot_timeseries() can derive it from minage
    expect_null(captured$ylab, info = fn)
    # pass-through arguments survive unchanged
    expect_identical(captured$add_ci, TRUE, info = fn)
    expect_identical(captured$lwd,    5,    info = fn)
  }
})

test_that("an explicit ylab overrides the derived default", {
  captured <- NULL
  testthat::local_mocked_bindings(
    plot_timeseries = function(Rceattle, output, ylab, ...) {
      captured <<- list(output = output, ylab = ylab)
      invisible(NULL)
    }
  )
  Rceattle::plot_recruitment("dummy_model", ylab = "Recruits (billions)")
  expect_identical(captured$ylab, "Recruits (billions)")
})

test_that("axis labels state the units the plotter actually rescales to", {
  # The pairing of divisor and label is the whole point: recruitment is carried
  # in thousands of fish and was for a long time plotted unscaled under a
  # "million" label. Assert both halves against each other.
  ylab <- get(".rce_ts_ylab", envir = asNamespace("Rceattle"))
  scale <- get(".RCE_TS_RESCALE", envir = asNamespace("Rceattle"))

  expect_identical(ylab("biomass", 1),             "Biomass (million mt)")
  expect_identical(ylab("ssb", 1),                 "SSB (million mt)")
  expect_identical(ylab("R", 1),                   "Age-1 recruits (millions)")
  expect_identical(ylab("exploitable_biomass", 1), "Max exploitable biomass (million mt)")
  expect_identical(ylab("ssb_depletion", 1),       "SSB depletion")
  expect_identical(ylab("biomass_depletion", 1),   "Biomass depletion")

  # Only recruitment names an age (it is an age class); the aggregates do not,
  # so minage cannot leak into their labels.
  expect_identical(ylab("R", 3),       "Age-3 recruits (millions)")
  expect_identical(ylab("biomass", 3), "Biomass (million mt)")
  expect_identical(ylab("ssb", 3),     "SSB (million mt)")
  # one shared y axis cannot name two different minimum ages
  expect_identical(ylab("R", c(1, 3)), "recruits (millions)")

  # every rescaled series names its rescaled unit; the unscaled ones name none
  expect_identical(unname(scale[c("biomass", "ssb", "exploitable_biomass")]),
                   rep(1e6, 3))
  expect_identical(unname(scale[["R"]]), 1e3)
  for (out in names(scale)) {
    expect_true(grepl("million", ylab(out, 1)), info = out)
  }
  for (out in c("ssb_depletion", "biomass_depletion")) {
    expect_true(is.na(scale[out]), info = out)
    expect_false(grepl("million", ylab(out, 1)), info = out)
  }
})

test_that("generated wrappers keep the documented public argument list", {
  # The wrappers pin output but must otherwise expose the exact signature users
  # depend on (partial-arg matching, introspection). Guard it explicitly.
  # ylab is appended, not inserted: a positional third argument has been
  # model_names on every released version.
  api_args <- c("Rceattle", "file", "model_names", "line_col", "species",
                "spnames", "add_ci", "lwd", "save", "right_adj", "legend.pos",
                "width", "height", "minyr", "maxyr", "incl_proj", "mod_cex",
                "lty", "alpha", "mod_avg", "mse", "OM", "reference", "ylab")
  for (fn in c("plot_biomass", "plot_recruitment", "plot_ssb",
               "plot_exploitable_biomass", "plot_depletionSSB", "plot_depletion")) {
    expect_identical(names(formals(get(fn, envir = asNamespace("Rceattle")))),
                     api_args, info = fn)
  }
})


testthat::test_that("a single-species model gets no species facet", {
  testthat::skip_on_cran()
  testthat::skip_if_not_installed("ggplot2")
  # GOApollock is genuinely one species. BS2017SS is THREE species run in
  # single-species MODE, so it is the wrong fixture for this.
  fit <- suppressWarnings(suppressMessages(Rceattle::fit_mod(
    Rceattle::GOApollock, inits = NULL, file = NULL, estimateMode = 1,
    msmMode = 0, random_rec = FALSE,
    fit_control = Rceattle::fit_control(phase = FALSE, getsd = FALSE,
                                        verbose = 0))))
  testthat::expect_equal(fit$data_list$nspp, 1)

  is_faceted <- function(p) {
    !identical(class(ggplot2::ggplot_build(p)$layout$facet)[1], "FacetNull")
  }
  for (f in c(Rceattle::plot_biomass, Rceattle::plot_ssb,
              Rceattle::plot_recruitment, Rceattle::plot_depletionSSB)) {
    p <- suppressWarnings(suppressMessages(f(fit)))
    testthat::expect_false(is_faceted(p))
  }

  # ...and a multi-species model still is.
  ms <- suppressWarnings(suppressMessages(Rceattle::fit_mod(
    Rceattle::BS2017SS, inits = NULL, file = NULL, estimateMode = 1,
    msmMode = 0, random_rec = FALSE,
    fit_control = Rceattle::fit_control(phase = FALSE, getsd = FALSE,
                                        verbose = 0))))
  testthat::expect_gt(ms$data_list$nspp, 1)
  testthat::expect_true(is_faceted(
    suppressWarnings(suppressMessages(Rceattle::plot_biomass(ms)))))
})

testthat::test_that("absolute-scale quantities include zero on the y-axis", {
  testthat::skip_on_cran()
  testthat::skip_if_not_installed("ggplot2")
  fit <- suppressWarnings(suppressMessages(Rceattle::fit_mod(
    Rceattle::GOApollock, inits = NULL, file = NULL, estimateMode = 1,
    msmMode = 0, random_rec = FALSE,
    fit_control = Rceattle::fit_control(phase = FALSE, getsd = FALSE,
                                        verbose = 0))))
  ymin <- function(p) {
    ggplot2::ggplot_build(p)$layout$panel_params[[1]]$y.range[1]
  }
  # Biomass, SSB and recruitment are read against zero, so a truncated axis
  # overstates how much they move.
  for (f in c(Rceattle::plot_biomass, Rceattle::plot_ssb,
              Rceattle::plot_recruitment, Rceattle::plot_exploitable_biomass)) {
    testthat::expect_lte(ymin(suppressWarnings(suppressMessages(f(fit)))), 0)
  }
})


# --- log-scale confidence intervals -------------------------------------------
# Biomass/SSB/recruitment intervals are taken on the log scale when the model
# reports a matching `log_*` series. Built from a synthetic model rather than a
# fit so the arithmetic is checked exactly and the test stays fast.
.fake_ts_model <- function(output, value, sd_nat, sd_log = NULL,
                           styr = 2000L, minage = 1) {
  nyrs <- length(value)
  q <- matrix(value, nrow = 1)
  sdval <- stats::setNames(value, rep(output, nyrs))
  sdsd  <- sd_nat
  if (!is.null(sd_log)) {
    sdval <- c(sdval, stats::setNames(log(value), rep(paste0("log_", output), nyrs)))
    sdsd  <- c(sdsd, sd_log)
  }
  structure(list(
    data_list  = list(spnames = "Sp", nspp = 1L, minage = minage,
                      styr = styr, endyr = styr + nyrs - 1L,
                      projyr = styr + nyrs - 1L, estDynamics = 0,
                      Ptarget = 0.4, Plimit = 0.2),
    quantities = stats::setNames(list(q), output),
    sdrep      = list(value = sdval, sd = sdsd)
  ), class = "Rceattle")
}

test_that("a requested interval that cannot be drawn warns instead of vanishing", {
  testthat::skip_if_not_installed("ggplot2")
  # Silently rendering an empty ribbon is how plot_exploitable_biomass() and
  # plot_depletion*() hid a missing ADREPORT for years.
  m <- .fake_ts_model("R", c(5e5, 3e5), c(1e5, 5e4))
  m$sdrep$value <- m$sdrep$value[0]; m$sdrep$sd <- m$sdrep$sd[0]
  expect_warning(Rceattle::plot_recruitment(m, add_ci = TRUE),
                 "no standard errors")
})

test_that("log-scale intervals are right-skewed and never reach zero", {
  testthat::skip_if_not_installed("ggplot2")
  # A weak year class with large uncertainty: the symmetric interval would put
  # the lower bound below zero, which is what the log scale exists to avoid.
  value  <- c(5e5, 1e4, 4e5)
  sd_nat <- c(1e5, 8e3, 9e4)
  sd_log <- c(0.2, 0.8, 0.25)

  p <- Rceattle::plot_recruitment(
    .fake_ts_model("R", value, sd_nat, sd_log), add_ci = TRUE)
  d <- p$data[order(p$data$Year), ]

  # Plotted on the recruitment scale (thousands of fish -> millions)
  expect_equal(d$value, value / 1e3)
  expect_equal(d$lower95, exp(log(value) - 1.92 * sd_log) / 1e3)
  expect_equal(d$upper95, exp(log(value) + 1.92 * sd_log) / 1e3)

  # Strictly positive, and skewed away from the line on the high side
  expect_true(all(d$lower95 > 0))
  expect_true(all((d$upper95 - d$value) > (d$value - d$lower95)))

  # The symmetric interval this replaces would have gone negative
  expect_lt(min(value - 1.92 * sd_nat), 0)
})

test_that("a model without log_* gets the log interval derived from sd/value", {
  testthat::skip_if_not_installed("ggplot2")
  # sd(log x) = sd(x)/x is the delta method's own identity, so a series with
  # only a natural-scale SD -- a pre-log_* fit, or exploitable_biomass and the
  # depletions, which cannot be ADREPORTed on the log scale -- still gets a
  # right-skewed interval rather than a symmetric one.
  value  <- c(5e5, 3e5, 4e5)
  sd_nat <- c(1e5, 5e4, 9e4)

  p <- Rceattle::plot_recruitment(
    .fake_ts_model("R", value, sd_nat), add_ci = TRUE)
  d <- p$data[order(p$data$Year), ]

  expect_equal(d$lower95, exp(log(value) - 1.92 * sd_nat / value) / 1e3)
  expect_equal(d$upper95, exp(log(value) + 1.92 * sd_nat / value) / 1e3)
  expect_true(all(d$lower95 > 0))

  # ...and identical to what an explicitly reported log_* row would give
  q <- Rceattle::plot_recruitment(
    .fake_ts_model("R", value, sd_nat, sd_log = sd_nat / value), add_ci = TRUE)
  expect_equal(d$lower95, q$data[order(q$data$Year), ]$lower95)
  expect_equal(d$upper95, q$data[order(q$data$Year), ]$upper95)
})

test_that("a zero-valued series keeps the symmetric interval", {
  testthat::skip_if_not_installed("ggplot2")
  # exploitable_biomass is identically 0 without projection F; sd/value is NaN
  # there, and the degenerate symmetric interval is the right answer.
  p <- Rceattle::plot_recruitment(
    .fake_ts_model("R", c(0, 3e5), c(0, 5e4)), add_ci = TRUE)
  d <- p$data[order(p$data$Year), ]
  expect_equal(d$lower95[1], 0)
  expect_equal(d$upper95[1], 0)
  expect_true(d$lower95[2] > 0)
})
