# =============================================================================
# Canonical workbook-column schema
# =============================================================================
#
# The Rceattle data workbook's column dictionary historically lived in FOUR
# unsynchronized, hand-maintained copies (with a literal "kept in sync by eye"
# note): the `R/data.R` roxygen `@format`, the embedded `meta_data_names.xlsx`,
# `write_data()`'s ordered `row_labels` / `bioenergetics_control` vectors, and
# `switch_check()`'s per-column defaults. They drifted -- ~20 used-but-
# undocumented columns, stale entries, a case mismatch, legacy names.
#
# This file is the single source of truth for "what a workbook column is": one
# row per column (or per control-sheet / bioenergetics-sheet scalar), carrying
# its name, sheet, type, default, allowed values, TMB target, documentation, and
# deprecated aliases. It mirrors the row-list-keyed-by-name idiom of
# `R/1-data_requirements_table.R` (the data-element requirement table); this is
# the per-COLUMN analogue.
#
# Consumers (each replaces one hand-copy):
#   * `switch_check()`      -- per-column defaults + deprecated-name migration.
#   * `write_data()`        -- control `row_labels` + `bioenergetics` label order.
#   * meta_data_names.xlsx  -- regenerated by `.rce_build_meta_data_df()`.
#   * `R/data.R` roxygen    -- guarded against `doc` by a drift-detector test.
#
# Each row is a list with fields:
#   name        chr  column / control-scalar name (identity + lookup key).
#   sheet       chr  "control" | "fleet_control" | "bioenergetics_control".
#   type        chr  "integer" | "numeric" | "character" | "switch".
#   doc         chr  the canonical description (drives the xlsx `Description`
#                    column and, after Phase 3, the roxygen `\item`).
#   meta        lgl  TRUE if the column appears in the `meta_data` sheet.
#   has_default lgl  TRUE if a default is filled when the column/scalar is absent.
#                    WIRED for `sheet == "fleet_control"` only: switch_check()
#                    reads the value + message from here via `.rce_apply_default()`.
#                    For control / bioenergetics scalars the `default` fields are
#                    DOCUMENTATION ONLY (like `aliases`) -- switch_check() fills
#                    those with hand-coded literals that carry per-species /
#                    `msmMode == 0` logic this table does not represent.
#   default          the default value (only meaningful when has_default). For a
#                    control/bio scalar it records the per-element value only.
#   default_msg chr  the exact `message()` switch_check emits on defaulting a
#                    fleet_control column (NULL = fill silently).
#   default_msg_when chr  name of a predicate gating the message (NULL = always);
#                    "np_hake" = only when a non-parametric/Hake/LogisticPM fleet
#                    is present (matches the current conditional messaging).
#   default_scope chr for control/bioenergetics scalars whose default is applied
#                    per-species or only in single-species mode; documentation
#                    only (switch_check keeps that imperative logic).
#   allowed     chr  name of the switch map in R/0-switches.R (NULL = free value).
#   aliases     chr  deprecated old names accepted on read (upgraded in place).
#   status      chr  "live" (used by the model) | "orphan" (documented but read
#                    nowhere -- excluded from generated docs once dropped).
#   tmb_target  chr  the downstream DATA_*/derived object, for reference.
#
# The `doc` string is the single authoritative description for each column: it
# is written verbatim into the generated `meta_data_names.xlsx` Description and
# is asserted, name-for-name, against the `R/data.R` roxygen `@format` items by
# the drift-guard in test-schema-canonical.R (so a rename or a new column that
# forgets its roxygen entry fails CI). Deprecated spellings live in `aliases`
# and are upgraded on read; keep the `doc` on the canonical names.

# ---- Row constructor: one call per column, non-default fields only -----------
.rce_col <- function(name, sheet, doc, type = "numeric",
                     meta = TRUE, has_default = FALSE, default = NULL,
                     default_msg = NULL, default_msg_when = NULL,
                     default_scope = NULL, allowed = NULL,
                     aliases = character(0), status = "live",
                     tmb_target = NA_character_) {
  list(name = name, sheet = sheet, doc = doc, type = type, meta = meta,
       has_default = has_default, default = default, default_msg = default_msg,
       default_msg_when = default_msg_when, default_scope = default_scope,
       allowed = allowed, aliases = aliases, status = status,
       tmb_target = tmb_target)
}

#' Canonical workbook-column schema
#'
#' @return A named list of column rows (see the file header for the field
#'   schema), keyed by canonical `name`. Consumed by `switch_check()`,
#'   `write_data()`, the `meta_data_names.xlsx` generator, and the roxygen
#'   drift-detector test.
#' @keywords internal
#' @noRd
.rce_column_schema <- function() {
  rows <- list(

    # ======================================================================
    # Control sheet (model dimensions + global scalars), in write order
    # ======================================================================
    .rce_col("nspp", "control", "Integer: number of species included in CEATTLE", type = "integer"),
    .rce_col("styr", "control", "Integer: start year of the hindcast", type = "integer"),
    .rce_col("endyr", "control", "Integer: end year of the hindcast", type = "integer"),
    .rce_col("projyr", "control", "Integer: end year of the forecast", type = "integer"),
    .rce_col("nsex", "control", "Integer: number of sexes to model in the population (1 = combined/1sex, 2 = models both female/male)", type = "integer"),
    .rce_col("spawn_month", "control", "Numeric: spawning month of the population to adjust the numbers at spawning"),
    # Documented historically in the roxygen dictionary but read nowhere and not
    # written to the workbook; carried as an orphan so the eventual drop is an
    # explicit, testable record rather than a silent omission.
    .rce_col("R_sexr", "control", "Percent of recruitment that is female (ignored if nsex = 1)", meta = FALSE, status = "orphan"),
    .rce_col("nages", "control", "Integer: number of ages of each species", type = "integer"),
    .rce_col("minage", "control", "Numeric: minimum age for each population (i.e. does recruitment correspond to age 0, 1, 2?)"),
    .rce_col("nlengths", "control", "Integer: number of lengths of each species", type = "integer"),
    .rce_col("pop_wt_index", "control", "Integer: weight index for calculating biomass, consumption/ration, and suitability for each species", type = "integer"),
    .rce_col("ssb_wt_index", "control", "Integer: weight index for calculating female spawning-stock biomass (SSB) for each species", type = "integer"),
    # Order matches write_data()'s control-sheet assembly (alpha/beta before the
    # age-transition index) so the write -> read round-trip preserves data_list
    # element order exactly, not just element values.
    .rce_col("alpha_wt_len", "control", "Alpha parameter from Weight = alpha * Length ^ beta", has_default = TRUE, default = 1e-6, default_msg = "'alpha_wt_len' not specified in data, assuming 1e-6"),
    .rce_col("beta_wt_len", "control", "Beta parameter from Weight = alpha * Length ^ beta", has_default = TRUE, default = 3, default_msg = "'beta_wt_len' not specified in data, assuming 3"),
    .rce_col("pop_age_transition_index", "control", "Integer: age transition matrix (e.g. growth trajectory) index to use deriving length-based predation", type = "integer"),
    .rce_col("sigma_rec", "control", "Numeric: fixed or initial value of standard deviation for recruitment deviates", aliases = "sigma_rec_prior"),
    .rce_col("other_food", "control", "Numeric: other food in the ecosystem for each species (kg)"),
    .rce_col("estDynamics", "control", "Integer: switch to estimate or fix numbers-at-age: \r\n0 = estimate dynamics\r\n1 = use input numbers-at-age in NbyageFixed, \r\n2 = multiply input numbers-at-age (NbyageFixed) by a single scaling coefficient\r\n3 = multiply input numbers-at-age (NbyageFixed) by age specific scaling coefficient.", type = "switch", allowed = "estDynamics_map", has_default = TRUE, default = 0, default_msg = "'estDynamics' are not included in data, assuming 0", default_scope = "per-species (rep(0, nspp)); documentation-only"),

    # ======================================================================
    # fleet_control sheet, in canonical column order
    # ======================================================================
    .rce_col("Fleet_name", "fleet_control", "Name of survey or fishery", type = "character"),
    .rce_col("Fleet_code", "fleet_control", "Index of survey/fishery (does not restart for each species)", type = "integer"),
    .rce_col("Fleet_type", "fleet_control", "0 = Do not estimate (fixes all parameters for this fleet to initial values)\r\n1 = Fishery\r\n2 = Survey", type = "switch", allowed = "fleet_map"),
    .rce_col("Species", "fleet_control", "Species number", type = "integer"),
    .rce_col("Selectivity_index", "fleet_control", "Index to mirror selectivities (otherwise, same as fleet_code)", type = "integer"),
    .rce_col("Selectivity", "fleet_control", "0 = fixed (empirical selectivity from srv_emp_sel)\r\n1 = logistic\r\n2 = non-parametric (Ianelli et al. 2018)\r\n3 = double logistic\r\n4 = descending logistic\r\n5 = non-parametric (Taylor et al. 2014, 'Hake')\r\n6 = 2D AR1 (age x year)\r\n7 = 3D AR1 (Cheng et al. 2024)\r\n8 = double normal\r\n9 = non-parametric random walk (AMAK 'pm')\r\n11 = logistic with a free age-1 selectivity (AMAK 'pm')\r\nWhether a form is age- or length-based is set by Selectivity_dimension, not by the code.", type = "switch", allowed = "sel_map"),
    .rce_col("Selectivity_dimension", "fleet_control", "\"Age\" or \"Length\".", type = "character", meta = TRUE, has_default = TRUE, default = "Age", default_msg = "'Selectivity_dimension' not specified in 'fleet_control', assuming 'Age'", default_msg_when = "growth_estimated"),
    .rce_col("N_sel_bins", "fleet_control", "Number of age or length bins to estimate for non-parametric and AR1 selectivity (Selectivity = 2, 5, 6, 7, or 9).", type = "integer", aliases = "Nselages"),
    .rce_col("Sel_curve_pen1", "fleet_control", "Shape/smoothness penalty weight for non-parametric (type 2/9) and LogisticPM (11) selectivity (the intuitive alternative is Sel_shape_sd). The 2DAR1/3DAR1 forms (6/7) reuse this column as a logit-scale AR1 correlation.", has_default = TRUE, default = 0, default_msg = "'Sel_curve_pen1' not specified in 'fleet_control', assuming '0'", default_msg_when = "np_hake"),
    .rce_col("Sel_curve_pen2", "fleet_control", "2nd-difference curvature penalty weight for non-parametric (type 2/9) selectivity (the intuitive alternative is Sel_curvature_sd). The 2DAR1/3DAR1 forms (6/7) reuse this column as a logit-scale AR1 correlation.", has_default = TRUE, default = 0, default_msg = "'Sel_curve_pen2' not specified in 'fleet_control', assuming '0'", default_msg_when = "np_hake"),
    .rce_col("Sel_curve_pen3", "fleet_control", "Deviation-magnitude penalty weight (Sel_curve_pen3) for non-parametric / LogisticPM selectivity.", meta = TRUE, has_default = TRUE, default = 0, default_msg = "'Sel_curve_pen3' not specified in 'fleet_control', assuming '0'", default_msg_when = "np_hake"),
    .rce_col("Time_varying_sel", "fleet_control", "Whether to estimate time-varying selectivity for logistic, double logistic, descending logistic, or non-parametric forms.\r\n0 = no\r\n1 = penalized deviates given sel_sd_prior (or random effects if \"random_sel\" is selected in \"fit_mod\")\r\n3 = time blocks with no penalty\r\n4 = random walk following Dorn\r\n5 = random walk on the ascending portion of double logistic only.", type = "switch", allowed = "tv_sel_map"),
    .rce_col("Time_varying_sel_sd", "fleet_control", "The fixed or initial sd to use for time varying selectivity if set to 1, 4, or 5.", aliases = c("Sel_sd_prior", "Time_varying_sel_sd_prior")),
    .rce_col("Sel_start_year", "fleet_control", "First year the fleet's time-varying selectivity deviations are estimated and penalized (NA -> earliest year of data across fleets sharing the Selectivity_index, bounded below by styr).", type = "integer", meta = TRUE, has_default = TRUE, default = NA),
    .rce_col("Bin_first_selected", "fleet_control", "Age/length bin at which selectivity becomes non-zero", type = "integer", aliases = "Age_first_selected"),
    .rce_col("Sel_shape_sd", "fleet_control", "Shape/smoothness selectivity penalty expressed as a standard deviation (an intuitive alternative to Sel_curve_pen1); weight = 1/(2*sd^2). NonParametric (2/9) and LogisticPM (11).", meta = TRUE),
    .rce_col("Sel_curvature_sd", "fleet_control", "2nd-difference curvature selectivity penalty expressed as a standard deviation (Sel_curve_pen2); NonParametric-only.", meta = TRUE),
    .rce_col("Sel_devmag_sd", "fleet_control", "Deviation-magnitude selectivity penalty expressed as a standard deviation (Sel_curve_pen3). NonParametric (2/9) and LogisticPM (11).", meta = TRUE),
    .rce_col("Sel_shape_dir", "fleet_control", "Direction of the (directional-mode) NonParametric shape penalty when Sel_shape_sd is used: \"Decreasing\" (default) or \"Increasing\".", type = "character", meta = TRUE),
    .rce_col("Sel_pen_first_bin", "fleet_control", "First bin (age or length) for the non-parametric shape penalty (NA -> Bin_first_selected).", type = "integer", meta = TRUE, has_default = TRUE, default = NA, aliases = "Sel_pen_first_age"),
    .rce_col("Sel_pen_last_bin", "fleet_control", "Last (left) bin of the shape-penalty pairs (NA -> nbins-2).", type = "integer", meta = TRUE, has_default = TRUE, default = NA, aliases = "Sel_pen_last_age"),
    .rce_col("Sel_shape_mode", "fleet_control", "Shape-penalty mode: \"Directional\" (default) or \"Smooth\" (two-sided d^2, RTMB).", type = "character", meta = TRUE, has_default = TRUE, default = NA),
    .rce_col("Sel_avgsel_pen", "fleet_control", "Weight on the AMAK avgsel base-level penalty (type 9); 0 = off (default), 10 matches AMAK.", meta = TRUE, has_default = TRUE, default = 0),
    .rce_col("Sel_cap_bin", "fleet_control", "NonParametricRPM bin cap (NA -> no cap).", type = "integer", meta = TRUE, has_default = TRUE, default = NA, aliases = "Sel_cap_age"),
    .rce_col("Sel_norm_bin", "fleet_control", "Age/length bin at which selectivity = 1. \r\nIf NA, it will not normalize selectivity. \r\nIf < 0, will normalize selectivity by the max.", type = "integer", has_default = TRUE, default = NA, default_msg = "'Sel_norm_bin' not specified in 'fleet_control', assuming 'NA'", aliases = c("Age_max_selected", "Sel_norm_bin1")),
    .rce_col("Sel_norm_bin_upper", "fleet_control", "Upper age/length bin for selectivity normalization (default = NA). If NA, does not use the age range, If not NA, uses mean selectivity between `Sel_norm_bin` and `Sel_norm_bin_upper`", type = "integer", has_default = TRUE, default = NA, default_msg = "'Sel_norm_bin_upper' not specified in 'fleet_control', assuming 'NA'", default_msg_when = "sel_norm_upper", aliases = c("Age_max_selected_upper", "Sel_norm_bin2")),
    .rce_col("Comp_distribution", "fleet_control", "Composition data distribution:\r\n-1 = AFSC multinomial\r\n0 = full multinomial\r\n1 = dirichlet-multinomial", type = "switch", allowed = "comp_loglike_map", has_default = TRUE, default = "MultinomialAFSC", default_msg = "'Comp_distribution' not specified in 'fleet_control', assuming 'MultinomialAFSC'", aliases = "Comp_loglike"),
    .rce_col("Comp_weights", "fleet_control", "Composition weight, on a scale set by 'Comp_distribution'. \r\nUnder a multinomial it is the natural-scale multiplier on the input sample size. \r\nUnder a Dirichlet-multinomial the model uses exp(Comp_weights), so the column is the LOG of the starting weight -- the usual template value of 1 is a starting weight of e, not 1; use 0 for a weight of 1. \r\nRead when a model is built from scratch -- a refit keeps the weight it is given. \r\nSee 'Comp_weights_mcallister' for the weight a fit implies, and reweight_comps() to tune towards it."),
    .rce_col("CAAL_distribution", "fleet_control", "Composition data distribution:\r\n0 = full multinomial\r\n1 = dirichlet-multinomial", type = "switch", allowed = "comp_loglike_map", has_default = TRUE, default = "Multinomial", default_msg = "'CAAL_distribution' not specified in 'fleet_control', assuming 'Multinomial'", default_msg_when = "has_caal", aliases = "CAAL_loglike"),
    .rce_col("CAAL_weights", "fleet_control", "Conditional age-at-length composition weight, on a scale set by 'CAAL_distribution' (as for 'Comp_weights'). \r\nUnder a multinomial it is the natural-scale multiplier on the input sample size. \r\nUnder a Dirichlet-multinomial the model uses exp(CAAL_weights), so the column is the LOG of the starting weight -- the default of 1 is a starting weight of e, not 1. \r\nRead when a model is built from scratch -- a refit keeps the weight it is given.", has_default = TRUE, default = 1, default_msg = "'CAAL_weights' not specified in 'fleet_control', assuming 1", default_msg_when = "has_caal"),
    .rce_col("Comp_accum_young", "fleet_control", "Age/length composition young-tail accumulation bin (AFSC ac_yng): a 1-based ordinal on the fleet's composition dimension; bins below it are folded into it before the likelihood. NA or 1 = no young accumulation.", type = "integer", has_default = TRUE, default = NA),
    .rce_col("Comp_accum_old", "fleet_control", "Age/length composition old-tail accumulation bin (AFSC ac_old): a 1-based ordinal on the fleet's composition dimension; bins above it are folded into it before the likelihood. NA, 0, or a value >= the number of bins = no old accumulation.", type = "integer", has_default = TRUE, default = NA),
    .rce_col("Observation_units", "fleet_control", "1 = catch/index is weight (kg) the observation \r\n2 = catch/index is in numbers", type = "integer", aliases = c("Weight1_Numbers2", "weight1_Numbers2")),
    .rce_col("Weight_index", "fleet_control", "Weight index to use for calculation of derived quantities", type = "integer"),
    .rce_col("Age_transition_index", "fleet_control", "Age transition matrix (e.g. growth trajectory) index to used convert age to length", type = "integer"),
    .rce_col("Catchability_index", "fleet_control", "index to use if catchability coefficients are to be set the same", type = "integer", aliases = "Q_index"),
    .rce_col("Catchability", "fleet_control", "Catchability form. Accepts integer codes or readable strings:\r\n0 or \"Fixed\" = fixed at Catchability_init\r\n1 or \"Estimated\" = estimate as a free parameter\r\n2 or \"Estimated-with-prior\" = estimate with a normal prior N(Catchability_init, Catchability_prior_sd)\r\n3 or \"Analytical\" = geometric-mean analytical q following Ludwig and Walters 1994\r\n4 or \"PowerEquation\" = power equation (NOT YET IMPLEMENTED)\r\n5 or \"Environmental\" = linear equation log(q_y) = q_mu + beta * index_y; the environmental index is specified by Time_varying_q\r\n6 or \"AR1\" = AR1 random deviates fit to an environmental index (sensu Rogers et al 2024; 10.1093/icesjms/fsae005), index specified by Time_varying_q\r\n7 or \"AnalyticalArith\" = arithmetic-mean analytical q (AMAK/ebswp form, pair with the MVN survey likelihood)", type = "switch", allowed = "q_map", aliases = "Estimate_q"),
    .rce_col("Catchability_init", "fleet_control", "Starting value or fixed value for catchability", aliases = c("Q_prior", "Q_init")),
    .rce_col("Catchability_prior_sd", "fleet_control", "Standard deviation for q prior", aliases = "Q_sd_prior"),
    .rce_col("Time_varying_q", "fleet_control", "0 = no\r\n1 = penalized deviate or random effect \r\n3 = time blocks with no penalty\r\n4 = random walk from mean following Dorn 2018 (dnorm(q_y - q_y-1, 0, sigma)\r\nIf Catchability = 5, this determines the environmental index to be used in the equation log(q_y) = q_mu + beta * index_y\r\nIf \"random_q\" is selected in fit_mod, penalized deviates (1) and random walk parameters (4) will be treated as random effects", type = "switch", allowed = "tv_q_map"),
    .rce_col("Time_varying_q_sd", "fleet_control", "starting or fixed sd to use for the random walk of time varying q if set to 1", aliases = "Time_varying_q_sd_prior"),
    .rce_col("Estimate_index_sd", "fleet_control", "0 = use input \"Log_sd\" from index_data\r\n1 = estimate as free parameter\r\n2 = estimate analytically following Ludwig and Walters (1994)", type = "switch", allowed = "estimate_sd_map", aliases = "Estimate_survey_sd"),
    .rce_col("Index_sd", "fleet_control", "Starting value to be used if \"Estimate_index_sd\" = 1", aliases = c("Survey_sd_prior", "Index_sd_prior")),
    .rce_col("Estimate_catch_sd", "fleet_control", "0 = use input \"Log_sd\" from catch_data\r\n1 = estimate as free parameter\r\n2 = estimate analytically following Ludwig and Walters (1994)", type = "switch", allowed = "estimate_sd_map"),
    .rce_col("Catch_sd", "fleet_control", "Starting value to be used if Estimate_catch_sd = 1", aliases = "Catch_sd_prior"),
    .rce_col("Index_distribution", "fleet_control", "Survey/index biomass observation likelihood family. 0 or \"Lognormal\" (default) = independent lognormal; \"MVN\"/\"MVNORM\" use a multivariate normal with a user-supplied covariance in index_cov.", type = "switch", allowed = "index_distribution_map", meta = TRUE, has_default = TRUE, default = "Lognormal", aliases = "Index_loglike"),
    .rce_col("Month", "fleet_control", "Observation month for the fleet (0 = not specified).", type = "integer", meta = TRUE, has_default = TRUE, default = 0, default_msg = "'Month' not specified in 'fleet_control', assuming 0"),
    .rce_col("Proj_F_proportion", "fleet_control", "The proportion of future fishing mortality assigned to this fleet", aliases = "proj_F_prop"),

    # ---- Orphans: documented historically but read nowhere in the model ----
    .rce_col("Catch_units", "fleet_control", "Units used for survey: 1 = kg; 2 = numbers", meta = FALSE, status = "orphan"),
    .rce_col("Sex", "fleet_control", "sex codes: 0=combined; 1=use female only; 2=use male only; 3 = joint female and male", meta = FALSE, status = "orphan"),

    # ======================================================================
    # bioenergetics_control sheet, in write order
    # ======================================================================
    .rce_col("Ceq", "bioenergetics_control", "Integer: switch for which bioenergetics equation to use for each species for ft to scale max consumption: \r\n1 = Exponential (Stewart et al 1983)\r\n2 = Temperature-dependence for warm-water species (Kitchell et al 1977; sensu Holsman et al 2015)\r\n3 = temperature dependence for cool and cold-water species (Thornton and Lessem 1979)\r\n4 = for direct input of consumption in Pyrs  where consumption at age = Numbers * Pyrs (CA set to 1, fday set to 1, CB set to 0)", type = "integer", has_default = TRUE, default = 1L, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Cindex", "bioenergetics_control", "Integer: which environmental index in env_data to use to drive bioenergetics", type = "integer", has_default = TRUE, default = 0L, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Pvalue", "bioenergetics_control", "Numeric: this scales the maximum consumption used for ration for each species; Pvalue is in Cmax*fT*Pvalue*Pyrs", has_default = TRUE, default = 1, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("fday", "bioenergetics_control", "Numeric: number of foraging days per year for each species", has_default = TRUE, default = 365, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CA", "bioenergetics_control", "Intercept of allometric mass function for calculating maximum consumption: CA * Weight ^ CB", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CB", "bioenergetics_control", "Slope of allometric mass function for calculating maximum consumption: CA * Weight ^ CB", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Qc", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Tco", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Tcm", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Tcl", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CK1", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CK4", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    # Per-predator-species vectors defaulted by switch_check
    # (rep(0, nspp) / rep(1, nspp)); their defaulting stays imperative there.
    .rce_col("Diet_distribution", "bioenergetics_control", "Diet composition likelihood distribution per predator species:\r\n0 = multinomial\r\n1 = dirichlet-multinomial", type = "switch", allowed = "diet_loglike_map", meta = TRUE, aliases = "Diet_loglike"),
    .rce_col("Diet_comp_weights", "bioenergetics_control", "Diet composition weight per predator species, on a scale set by 'Diet_distribution' (as for 'Comp_weights'). \r\nUnder a multinomial it is the natural-scale multiplier on the input sample size. \r\nUnder a Dirichlet-multinomial the model uses exp(Diet_comp_weights), so the column is the LOG of the starting weight. \r\nRead when a model is built from scratch -- a refit keeps the weight it is given.", meta = TRUE)
  )

  names(rows) <- vapply(rows, function(r) r$name, character(1))
  rows
}

# -----------------------------------------------------------------------------
# Accessors over the schema
# -----------------------------------------------------------------------------

#' Apply a column's schema default when the value is absent.
#'
#' Reproduces `switch_check()`'s local `set_default(val, default, msg)`: when
#' `val` is NULL, emit the schema's `default_msg` (gated by `default_msg_when`)
#' and return the schema `default`; otherwise return `val` unchanged. Sourcing
#' the value and message from the schema is what removes the hand-copied
#' defaults from `switch_check()`.
#'
#' @param val The current column value (NULL if the column is absent).
#' @param col Canonical column name (schema key).
#' @param schema A prefetched `.rce_column_schema()` (avoids rebuilding it per
#'   call).
#' @param np_hake Value of the non-parametric/Hake/LogisticPM predicate, for
#'   columns whose message only fires when such a fleet is present
#'   (`default_msg_when == "np_hake"`).
#' @keywords internal
#' @noRd
.rce_apply_default <- function(val, col, schema = .rce_column_schema(),
                               np_hake = FALSE, conditions = list()) {
  if (!is.null(val)) return(val)
  row <- schema[[col]]
  if (is.null(row) || !isTRUE(row$has_default))
    stop("Internal: no schema default for column '", col, "'")
  msg  <- row$default_msg
  # A gated default message fires only when its condition holds -- so we don't
  # nag about an optional input the current model configuration never uses (e.g.
  # a CAAL distribution for a model with no CAAL data). The gate is named in the
  # schema's `default_msg_when`; `np_hake` is the legacy first-class gate, every
  # other named gate is supplied in `conditions` (a named logical list computed by
  # switch_check()). An ungated message (no `default_msg_when`) always fires.
  gate <- row$default_msg_when
  if (!is.null(gate) && nzchar(gate)) {
    on <- if (identical(gate, "np_hake")) isTRUE(np_hake) else isTRUE(conditions[[gate]])
    if (!on) msg <- NULL
  }
  if (!is.null(msg)) message(msg)
  row$default
}

#' Upgrade deprecated fleet_control column names to canonical, in place.
#'
#' The single migration point for legacy fleet_control column names: every
#' canonical column carries its historical spellings in the schema `aliases`
#' field, and this walks them, renaming any present old name to the canonical
#' one. Both `read_data()` (on the xlsx path) and `switch_check()` (on every
#' fit path) call it, so a data list built either way is upgraded identically
#' from the one schema -- the hand-coded rename cascades that used to live in
#' both are gone.
#'
#' Double-fire-safe: a no-op when the old name is absent (so re-running on an
#' already-upgraded list is silent), and it never clobbers an existing
#' canonical column. Emits one deprecation message per rename actually applied.
#'
#' @param fc A `fleet_control` data frame (or NULL).
#' @return `fc` with any deprecated column names upgraded to canonical.
#' @keywords internal
#' @noRd
.rce_upgrade_fleet_control_aliases <- function(fc) {
  if (is.null(fc)) return(fc)
  schema <- .rce_column_schema()
  for (row in schema) {
    if (row$sheet != "fleet_control" || length(row$aliases) == 0L) next
    for (old in row$aliases) {
      if (!is.null(fc[[old]])) {
        if (is.null(fc[[row$name]])) fc[[row$name]] <- fc[[old]]
        fc[[old]] <- NULL
        message(sprintf("'%s' is deprecated; use '%s'.", old, row$name))
      }
    }
  }
  fc
}

#' Upgrade deprecated data_list-level (control / bioenergetics) names to canonical.
#'
#' The analogue of `.rce_upgrade_fleet_control_aliases()` for the top-level
#' data_list elements that are NOT fleet_control columns -- the control scalars
#' and bioenergetics per-species vectors, whose deprecated names live in the
#' same schema `aliases` field (e.g. `sigma_rec_prior` -> `sigma_rec`,
#' `Diet_loglike` -> `Diet_distribution`). Double-fire-safe; one message per
#' rename applied.
#'
#' @param data_list An Rceattle data list (or NULL).
#' @return `data_list` with any deprecated control/bioenergetics element names
#'   upgraded to canonical.
#' @keywords internal
#' @noRd
.rce_upgrade_data_list_aliases <- function(data_list) {
  if (is.null(data_list)) return(data_list)
  schema <- .rce_column_schema()
  for (row in schema) {
    if (row$sheet == "fleet_control" || length(row$aliases) == 0L) next
    for (old in row$aliases) {
      if (!is.null(data_list[[old]])) {
        if (is.null(data_list[[row$name]])) data_list[[row$name]] <- data_list[[old]]
        data_list[[old]] <- NULL
        message(sprintf("'%s' is deprecated; use '%s'.", old, row$name))
      }
    }
  }
  data_list
}

#' Rows for one sheet, in schema (write) order.
#' @keywords internal
#' @noRd
.rce_schema_rows <- function(sheet, include_orphans = FALSE) {
  rows <- .rce_column_schema()
  rows <- Filter(function(r) r$sheet == sheet, rows)
  if (!include_orphans) rows <- Filter(function(r) r$status != "orphan", rows)
  rows
}

#' Canonical column/scalar names for one sheet, in write order.
#' @keywords internal
#' @noRd
.rce_schema_names <- function(sheet, include_orphans = FALSE) {
  unname(vapply(.rce_schema_rows(sheet, include_orphans),
                function(r) r$name, character(1)))
}

# -----------------------------------------------------------------------------
# meta_data sheet generator (the embedded workbook dictionary)
# -----------------------------------------------------------------------------
#
# The meta_data sheet is a 3-column [Sheet name | Column/row name | Description]
# frame documenting every control scalar, fleet_control column, and
# bioenergetics scalar, with a per-sheet header row for the remaining data
# sheets and a block of free-text NOTE rows at the end. This generator emits the
# schema-driven rows; the sheet-header + NOTE footer is a static template.

# Per-sheet header rows (Column/row name is NA, Description names the sheet).
.RCE_META_SHEET_HEADERS <- list(
  c("fleet_control",   "Survey and fishery data specifications"),
  c("index_data",      "Survey index or fishery indices in weight (kg) or numbers."),
  c("catch_data",      "Total catch in weight (mt) or numbers data"),
  c("comp_data",       "Survey/fishery age or length composition data. Note if sex is 3, put female composition data then male composition data (similar to SS)."),
  c("caal_data",       "Survey/fishery CAAL data. Note if sex is 3, put female CAAL data then male CAAL data (similar to SS)."),
  c("emp_sel",         "Empirical/fixed selectivity for surveys and fisheries (leave empty if not used)"),
  c("age_trans_matrix","Age transition matrix (e.g. growth trajectory) used to convert age to length for length comp data. \r\nCan have multiple matrices for a species specified by Age_transition_index."),
  c("age_error",       "Aging error matrices. Can have only one per species."),
  c("weight",          "Time-invariant or -varying empirical weight-at-age for calculation of derived quantities (SSB, Consumption/Ration, Suitability, Total Catch, Survey Biomass, etc). \r\nCan have multiple weight-at-age data-sets for each species."),
  c("maturity",        "Maturity-at-age for each species"),
  c("sex_ratio",       "Percent female at age for each species"),
  c("M1_base",         "Residual natural mortality for each species")
)

# env_data / ration_data / diet_data headers sit after the bioenergetics block.
.RCE_META_SHEET_HEADERS_TAIL <- list(
  c("env_data",    "Environmental indices such as bottom temperature data to incorporate into ration equation specified by Ceq and Cindex. Also used to drive catchability if Catchability = 5 or 6. Will use the mean for missing years. Temperature should be in Celsius."),
  c("ration_data", "Annual relative foraging rate by age. Multiplied by pvalue and fday to scale maximum consumption to the number of days in a year that foraging occurs."),
  c("diet_data",   "Stomach proportion by weight for each predator, prey, predator age, prey age combination. Multiple diet-data formats can be included:\r\n\r\n1) If Pred_age >= 0 and Prey_age >= 0, data is assumed to be  diet proportion of prey-at-age/sex in predator-at-age/sex. \r\n2) If Pred_age >= 0 and Prey_age < 0, data is assumed to be mean diet proportion of prey-spp in predator-at-age/sex (sum across prey ages and sexes)\r\n3) If Pred_age < 0 and Prey_age < 0, data is assumed to be  mean diet proportion of prey-spp in predator-spp (sum across prey ages/sexes and take mean across predator ages/sexes)\r\n4) If Pred_age < -500 and Prey_age < 0, data is assumed to be weighted mean diet proportion of prey-spp in predator-spp (sum across prey ages/sexes and take weighted mean across predator ages/sexes). Weights are estimated predators-at-age. \r\n\r\nIf \"Year = 0\", the the diet will be assumed to be the average between \"suit_styr\" and \"suit_endyr\". \r\n\r\nOnly diet-data type 1 can be used for MSVPA based suitability")
)

# Free-text NOTE / legend rows carried verbatim as the sheet footer.
.RCE_META_NOTES <- c(
  "NOTE: Most objects are ordered by species code if not specified",
  "NOTE: Lengths are index 1 through nlengths",
  "NOTE: Columns for ages are index by 1 through nages, but are placeholders.",
  "NOTE: For catch, index, and comp data, if \"Year\" is negative, it will predict for that year, but not include the data in the likelihood.",
  "NOTE: For emp_sel, weight, and ration_data, if \"Year\" == 0, those data will be used for all years"
)

#' Build the `meta_data` documentation sheet from the schema.
#'
#' Emits the control-scalar rows, the fleet_control header + column rows, the
#' data-sheet header rows, the bioenergetics-scalar rows, and the tail sheet
#' headers + NOTE footer -- reproducing the layout of the bundled
#' `meta_data_names.xlsx`.
#'
#' @return A data.frame with columns `Sheet name`, `Column/row name`,
#'   `Description`.
#' @keywords internal
#' @noRd
.rce_build_meta_data_df <- function() {
  add <- function(acc, sheet, col, desc) {
    rbind(acc, data.frame(`Sheet name` = sheet, `Column/row name` = col,
                          Description = desc, check.names = FALSE,
                          stringsAsFactors = FALSE))
  }
  out <- data.frame(`Sheet name` = character(0), `Column/row name` = character(0),
                    Description = character(0), check.names = FALSE,
                    stringsAsFactors = FALSE)

  # Control scalars (Sheet name "Control")
  for (r in .rce_schema_rows("control"))
    if (isTRUE(r$meta)) out <- add(out, "Control", r$name, r$doc)

  # fleet_control header + columns
  out <- add(out, "fleet_control", NA_character_, .RCE_META_SHEET_HEADERS[[1]][2])
  for (r in .rce_schema_rows("fleet_control"))
    if (isTRUE(r$meta)) out <- add(out, "fleet_control", r$name, r$doc)

  # Data-sheet headers (index_data .. M1_base)
  for (h in .RCE_META_SHEET_HEADERS[-1]) out <- add(out, h[1], NA_character_, h[2])

  # bioenergetics scalars
  for (r in .rce_schema_rows("bioenergetics_control"))
    if (isTRUE(r$meta)) out <- add(out, "bioenergetics_control", r$name, r$doc)

  # Tail sheet headers
  for (h in .RCE_META_SHEET_HEADERS_TAIL) out <- add(out, h[1], NA_character_, h[2])

  # NOTE footer (carried in the Sheet name column, as in the bundled file)
  for (n in .RCE_META_NOTES) out <- add(out, n, NA_character_, NA_character_)

  out
}
