# =============================================================================
# Canonical workbook-column schema
# =============================================================================
#
# This file is the single source of truth for "what a workbook column is": one
# row per column (or per control-sheet / bioenergetics-sheet scalar), carrying
# its name, sheet, type, default, allowed values, TMB target, documentation, and
# deprecated aliases. It mirrors the row-list-keyed-by-name idiom of
# `R/1-data_requirements_table.R` (the data-element requirement table); this is
# the per-COLUMN analogue.
#
# Consumers (each replaces one hand-copy):
#   * `switch_check()`      -- per-column defaults + deprecated-name migration.
#   * `write_data()`        -- control `row_labels` + `bioenergetics` label order.
#   * meta_data_names.xlsx  -- regenerated by `.rce_build_meta_data_df()`.
#   * `R/data.R` roxygen    -- guarded against `doc` by a drift-detector test.
#
# Each row is a list with fields:
#   name        chr  column / control-scalar name (identity + lookup key).
#   sheet       chr  "control" | "fleet_control" | "bioenergetics_control".
#   type        chr  "integer" | "numeric" | "character" | "switch".
#   doc         chr  the canonical description (drives the xlsx `Description`
#                    column and the roxygen `\item` in R/data.R).
#   meta        lgl  TRUE if the column appears in the `meta_data` sheet.
#   has_default lgl  TRUE if a default is filled when the column/scalar is absent.
#                    WIRED for `sheet == "fleet_control"` only: switch_check()
#                    reads the value + message from here via `.rce_apply_default()`.
#                    For control / bioenergetics scalars the `default` fields are
#                    DOCUMENTATION ONLY (like `aliases`) -- switch_check() fills
#                    those with hand-coded literals that carry per-species /
#                    `msmMode == 0` logic this table does not represent.
#   default          the default value (only meaningful when has_default). For a
#                    control/bio scalar it records the per-element value only.
#   default_msg chr  the exact `message()` switch_check emits on defaulting a
#                    fleet_control column (NULL = fill silently).
#   default_msg_when chr  name of a predicate gating the message (NULL = always);
#                    "np_hake" = only when a non-parametric/Hake/LogisticPM fleet
#                    is present (matches the current conditional messaging).
#   default_scope chr for control/bioenergetics scalars whose default is applied
#                    per-species or only in single-species mode; documentation
#                    only (switch_check keeps that imperative logic).
#   allowed     chr  name of the switch map in R/0-switches.R (NULL = free value).
#   aliases     chr  deprecated old names accepted on read (upgraded in place).
#   status      chr  "live" (used by the model) | "orphan" (documented but read
#                    nowhere -- excluded from generated docs once dropped).
#   tmb_target  chr  the object in the template this column feeds. Not always a
#                    plain rename: index_log_q_prior is log(Catchability_init).
#
# The `doc` string is the single authoritative description for each column: it
# is written verbatim into the generated `meta_data_names.xlsx` Description and
# is asserted, name-for-name, against the `R/data.R` roxygen `@format` items by
# the drift-guard in test-schema-canonical.R (so a rename or a new column that
# forgets its roxygen entry fails CI). Deprecated spellings live in `aliases`
# and are upgraded on read; keep the `doc` on the canonical names.

# ---- Row constructor: one call per column, non-default fields only -----------
.rce_col <- function(name, sheet, doc, type = "numeric",
                     meta = TRUE, has_default = FALSE, default = NULL,
                     default_msg = NULL, default_msg_when = NULL,
                     default_scope = NULL, allowed = NULL,
                     aliases = character(0), status = "live",
                     tmb_target = NA_character_) {
  list(name = name, sheet = sheet, doc = doc, type = type, meta = meta,
       has_default = has_default, default = default, default_msg = default_msg,
       default_msg_when = default_msg_when, default_scope = default_scope,
       allowed = allowed, aliases = aliases, status = status,
       tmb_target = tmb_target)
}

#' Canonical workbook-column schema
#'
#' @return A named list of column rows (see the file header for the field
#'   schema), keyed by canonical `name`. Consumed by `switch_check()`,
#'   `write_data()`, the `meta_data_names.xlsx` generator, and the roxygen
#'   drift-detector test.
#' @keywords internal
#' @noRd
.rce_column_schema <- function() {
  rows <- list(

    # ======================================================================
    # Control sheet (model dimensions + global scalars), in write order
    # ======================================================================
    .rce_col("nspp", "control", "Integer: number of species included in CEATTLE", type = "integer"),
    .rce_col("styr", "control", "Integer: start year of the hindcast", type = "integer"),
    .rce_col("endyr", "control", "Integer: end year of the hindcast", type = "integer"),
    .rce_col("projyr", "control", "Integer: end year of the forecast", type = "integer"),
    .rce_col("nsex", "control", "Integer: number of sexes to model in the population (1 = combined/1sex, 2 = models both female/male)", type = "integer"),
    .rce_col("spawn_month", "control", "Numeric: spawning month of the population to adjust the numbers at spawning"),
    # Documented historically in the roxygen dictionary but read nowhere and not
    # written to the workbook; carried as an orphan so the eventual drop is an
    # explicit, testable record rather than a silent omission.
    .rce_col("R_sexr", "control", "Percent of recruitment that is female (ignored if nsex = 1)", meta = FALSE, status = "orphan"),
    .rce_col("nages", "control", "Integer: number of ages of each species", type = "integer"),
    .rce_col("minage", "control", "Numeric: minimum age for each population (i.e. does recruitment correspond to age 0, 1, 2?)"),
    .rce_col("nlengths", "control", "Integer: number of lengths of each species", type = "integer"),
    .rce_col("pop_wt_index", "control", "Integer: weight index for calculating biomass, consumption/ration, and suitability for each species", type = "integer"),
    .rce_col("ssb_wt_index", "control", "Integer: weight index for calculating female spawning-stock biomass (SSB) for each species", type = "integer"),
    # Order matches write_data()'s control-sheet assembly (alpha/beta before the
    # age-transition index) so the write -> read round-trip preserves data_list
    # element order exactly, not just element values.
    .rce_col("alpha_wt_len", "control", "Alpha parameter from Weight = alpha * Length ^ beta", has_default = TRUE, default = 1e-6, default_msg = "'alpha_wt_len' not specified in data, assuming 1e-6"),
    .rce_col("beta_wt_len", "control", "Beta parameter from Weight = alpha * Length ^ beta", has_default = TRUE, default = 3, default_msg = "'beta_wt_len' not specified in data, assuming 3"),
    .rce_col("pop_age_transition_index", "control", "Integer: age transition matrix (e.g. growth trajectory) index to use deriving length-based predation", type = "integer"),
    .rce_col("sigma_rec", "control", "Numeric: fixed or initial value of standard deviation for recruitment deviates", aliases = "sigma_rec_prior"),
    .rce_col("other_food", "control", "Numeric: other food in the ecosystem for each species (kg)"),
    .rce_col("estDynamics", "control", "Integer: switch to estimate or fix numbers-at-age: \r\n0 = estimate dynamics\r\n1 = use input numbers-at-age in NbyageFixed, \r\n2 = multiply input numbers-at-age (NbyageFixed) by a single scaling coefficient\r\n3 = multiply input numbers-at-age (NbyageFixed) by age specific scaling coefficient.", type = "switch", allowed = "estDynamics_map", has_default = TRUE, default = 0, default_msg = "'estDynamics' are not included in data, assuming 0", default_scope = "per-species (rep(0, nspp)); documentation-only", tmb_target = "estDynamics"),

    # ======================================================================
    # fleet_control sheet, in canonical column order
    # ======================================================================
    .rce_col("Fleet_name", "fleet_control", "Name of survey or fishery", type = "character"),
    .rce_col("Fleet_code", "fleet_control", "Index of survey/fishery (does not restart for each species)", type = "integer"),
    .rce_col("Fleet_type", "fleet_control", "0 = Do not estimate (fixes all parameters for this fleet to initial values)\r\n1 = Fishery\r\n2 = Survey", type = "switch", allowed = "fleet_map", tmb_target = "flt_type"),
    .rce_col("Species", "fleet_control", "Species number", type = "integer", tmb_target = "flt_spp"),
    .rce_col("Month", "fleet_control", "Observation month for the fleet (0 = not specified).", type = "integer", meta = TRUE, has_default = TRUE, default = 0, default_msg = "'Month' not specified in 'fleet_control', assuming 0", tmb_target = "flt_month"),
    .rce_col("Selectivity_index", "fleet_control", "Index used to give fleets the SAME selectivity (otherwise, same as Fleet_code). Fleets sharing a value share one selectivity parameter block, and the penalties and priors on it are accumulated once, on the LEAD fleet -- the group's first non-Off fleet.\r\nSharing the parameters is not sufficient on its own: the columns that shape the curve are read per fleet, so they must match across the group or the fleets end up with different selectivities. Those are 'Selectivity', 'Selectivity_dimension', 'Bin_first_selected', 'N_sel_bins', 'Sel_norm_bin', 'Sel_norm_bin_upper', 'Sel_norm_scope' and 'Sel_cap_bin'; a blank counts as a value (a blank 'Sel_norm_bin' means 'do not normalize'). 'Time_varying_sel' and 'Sel_start_year' are instead resolved to the group's lead / earliest value, so a difference there is ignored rather than divergent. data_check() reports both cases.\r\nTo mirror a fleet, copy its fleet_control row and change only the identity and catchability columns.", type = "integer", tmb_target = "flt_sel_lead"),
    .rce_col("Selectivity", "fleet_control", "0 = fixed (empirical selectivity from srv_emp_sel)\r\n1 = logistic\r\n2 = non-parametric (Ianelli et al. 2018)\r\n3 = double logistic\r\n4 = descending logistic\r\n5 = non-parametric (Taylor et al. 2014, 'Hake')\r\n6 = 2D AR1 (age x year)\r\n7 = 3D AR1 (Cheng et al. 2024)\r\n8 = double normal\r\n9 = non-parametric random walk (AMAK 'pm')\r\n11 = logistic with a free age-1 selectivity (AMAK 'pm')\r\nWhether a form is age- or length-based is set by Selectivity_dimension, not by the code.", type = "switch", allowed = "sel_map", tmb_target = "flt_sel_type"),
    .rce_col("Selectivity_dimension", "fleet_control", "\"Age\" or \"Length\".", type = "character", meta = TRUE, has_default = TRUE, default = "Age", default_msg = "'Selectivity_dimension' not specified in 'fleet_control', assuming 'Age'", default_msg_when = "growth_estimated", tmb_target = "flt_sel_dim", allowed = "sel_dimension_map"),
    .rce_col("N_sel_bins", "fleet_control", "Number of age or length bins to estimate for non-parametric and AR1 selectivity (Selectivity = 2, 5, 6, 7, or 9).", type = "integer", aliases = "Nselages", tmb_target = "flt_n_sel_bins"),
    .rce_col("Sel_curve_pen1", "fleet_control", "Shape/smoothness penalty weight for non-parametric (type 2/9) and LogisticPM (11) selectivity (the intuitive alternative is Sel_shape_sd). The 2DAR1/3DAR1 forms (6/7) reuse this column as a logit-scale AR1 correlation, across selectivity BINS (ages or length bins, per Selectivity_dimension).", has_default = TRUE, default = 0, default_msg = "'Sel_curve_pen1' not specified in 'fleet_control', assuming '0'", default_msg_when = "np_hake"),
    .rce_col("Sel_curve_pen2", "fleet_control", "2nd-difference curvature penalty weight for non-parametric (type 2/9) selectivity (the intuitive alternative is Sel_curvature_sd). The 2DAR1/3DAR1 forms (6/7) reuse this column as a logit-scale AR1 correlation, across YEARS.", has_default = TRUE, default = 0, default_msg = "'Sel_curve_pen2' not specified in 'fleet_control', assuming '0'", default_msg_when = "np_hake"),
    .rce_col("Sel_curve_pen3", "fleet_control", "Deviation-magnitude penalty weight (Sel_curve_pen3) for non-parametric / LogisticPM selectivity. The 3DAR1 form (7) reuses this column as a logit-scale AR1 correlation, across COHORTS.", meta = TRUE, has_default = TRUE, default = 0, default_msg = "'Sel_curve_pen3' not specified in 'fleet_control', assuming '0'", default_msg_when = "np_hake"),
    .rce_col("Time_varying_sel", "fleet_control", "Whether to estimate time-varying selectivity for logistic, double logistic, descending logistic, or non-parametric forms.\r\n0 or \"Off\" = no\r\n1 or \"IID\" = penalized deviates given Time_varying_sel_sd (or random effects if \"random_sel\" is selected in \"fit_mod\")\r\n2 or \"AR1\" = REMOVED in 5.16.0; data_check() errors on it. It was never an AR1 -- the template scored it with the same independent normal penalty as \"IID\", and the selectivity deviations have no correlation parameter. Use \"IID\" for the fit it actually gave, or express the autocorrelation as a selectivity linkage: build_selectivity(linkages = list(inf_asc = linkage_spec(~ ar1(1 | Year), by = ~ fleet))).\r\n3 or \"Block\" = time blocks with no penalty\r\n4 or \"RandomWalk\" = random walk following Dorn\r\n5 or \"RandomWalkAscending\" = random walk on the ascending portion of double logistic only.\r\nSoft-deprecated as a whole: the linkage grammar expresses the same deviations per selectivity parameter, with the deviation sd estimated or fixed.", type = "switch", allowed = "tv_sel_map", tmb_target = "flt_varying_sel"),
    .rce_col("Time_varying_sel_sd", "fleet_control", "The fixed or initial sd to use for time varying selectivity if set to 1, 4, or 5.", aliases = c("Sel_sd_prior", "Time_varying_sel_sd_prior")),
    .rce_col("Sel_start_year", "fleet_control", "First year the fleet's time-varying selectivity deviations are estimated and penalized (NA -> earliest year of data across fleets sharing the Selectivity_index, bounded below by styr).", type = "integer", meta = TRUE, has_default = TRUE, default = NA, tmb_target = "flt_sel_start_yr"),
    .rce_col("Bin_first_selected", "fleet_control", "Age/length bin at which selectivity becomes non-zero", type = "integer", aliases = "Age_first_selected", tmb_target = "bin_first_selected"),
    .rce_col("Sel_shape_sd", "fleet_control", "Shape/smoothness selectivity penalty expressed as a standard deviation (an intuitive alternative to Sel_curve_pen1); weight = 1/(2*sd^2). NonParametric (2/9) and LogisticPM (11).", meta = TRUE),
    .rce_col("Sel_curvature_sd", "fleet_control", "2nd-difference curvature selectivity penalty expressed as a standard deviation (Sel_curve_pen2); NonParametric-only.", meta = TRUE),
    .rce_col("Sel_devmag_sd", "fleet_control", "Deviation-magnitude selectivity penalty expressed as a standard deviation (Sel_curve_pen3). NonParametric (2/9) and LogisticPM (11).", meta = TRUE),
    .rce_col("Sel_shape_dir", "fleet_control", "Direction of the (directional-mode) NonParametric shape penalty when Sel_shape_sd is used: \"Decreasing\" (default) or \"Increasing\".", type = "character", meta = TRUE, allowed = "sel_shape_dir_map"),
    .rce_col("Sel_pen_first_bin", "fleet_control", "First bin (age or length) for the non-parametric shape penalty (NA -> Bin_first_selected).", type = "integer", meta = TRUE, has_default = TRUE, default = NA, aliases = "Sel_pen_first_age", tmb_target = "flt_sel_pen_first_bin"),
    .rce_col("Sel_pen_last_bin", "fleet_control", "Last (left) bin of the shape-penalty pairs (NA -> nbins-2).", type = "integer", meta = TRUE, has_default = TRUE, default = NA, aliases = "Sel_pen_last_age", tmb_target = "flt_sel_pen_last_bin"),
    .rce_col("Sel_shape_mode", "fleet_control", "Shape-penalty mode: \"Directional\" (default) or \"Smooth\" (two-sided d^2, RTMB).", type = "character", meta = TRUE, has_default = TRUE, default = NA, tmb_target = "flt_sel_shape_mode", allowed = "sel_shape_mode_map"),
    .rce_col("Sel_avgsel_pen", "fleet_control", "Weight on the AMAK avgsel base-level penalty (type 9); 0 = off (default), 10 matches AMAK.", meta = TRUE, has_default = TRUE, default = 0, tmb_target = "flt_sel_avgsel_pen"),
    .rce_col("Sel_cap_bin", "fleet_control", "NonParametricRPM bin cap (NA -> no cap).", type = "integer", meta = TRUE, has_default = TRUE, default = NA, aliases = "Sel_cap_age", tmb_target = "flt_sel_cap_bin"),
    .rce_col("Sel_norm_bin", "fleet_control", "Age/length bin at which selectivity = 1. An absolute AGE for an age-based fleet (6 means age 6, not the 6th bin) or a 1-based LENGTH-BIN ordinal for a length-based one, per 'Selectivity_dimension'. \r\nIf NA, it will not normalize selectivity. \r\nIf < 0, will normalize selectivity by the max. \r\n\r\nIn a two-sex model this column says only WHERE the reference is taken; whether it is pooled across the sexes -- and so whether relative sex-specific selectivity survives -- is 'Sel_norm_scope'. NA does not normalize either way, leaving the relative scale free. \r\nRelative sex selectivity is only informed by the data where the composition is joint (comp_data Sex = 3); sex-specific rows (Sex = 1 or 2) each sum to 1 and carry no sex-ratio information. Selectivity = 'Hake' always normalizes within sex regardless of either column.", type = "integer", has_default = TRUE, default = NA, default_msg = "'Sel_norm_bin' not specified in 'fleet_control', assuming 'NA'", aliases = c("Age_max_selected", "Sel_norm_bin1"), tmb_target = "sel_norm_bin1"),
    .rce_col("Sel_norm_bin_upper", "fleet_control", "Upper age/length bin for selectivity normalization (default = NA). If NA, does not use the age range, If not NA, uses mean selectivity between `Sel_norm_bin` and `Sel_norm_bin_upper`", type = "integer", has_default = TRUE, default = NA, default_msg = "'Sel_norm_bin_upper' not specified in 'fleet_control', assuming 'NA'", default_msg_when = "sel_norm_upper", aliases = c("Age_max_selected_upper", "Sel_norm_bin2"), tmb_target = "sel_norm_bin2"),
    .rce_col("Sel_norm_scope", "fleet_control", "Whether selectivity normalization pools its reference across sexes. Orthogonal to 'Sel_norm_bin', which says WHERE the reference is taken (a named bin, or the max). \r\n\"WithinSex\" = each sex is divided by its own reference, so both reach 1 and only the SHAPE differs by sex (relative sex-specific selectivity removed). \r\n\"AcrossSexes\" (default) = one reference pooled over both sexes, so the less-selected sex stays below 1 (relative sex-specific selectivity retained). \r\nNo effect on a one-sex species, or where 'Sel_norm_bin' is NA (nothing is normalized). \r\nNOTE: before v5.8.0 a named bin always implied \"WithinSex\"; max-normalization always implied \"AcrossSexes\". Set this column explicitly to \"WithinSex\" to restore the old behaviour of a two-sex fleet that normalizes at a named bin.", type = "switch", allowed = "sel_norm_scope_map", has_default = TRUE, default = "AcrossSexes", default_msg = "'Sel_norm_scope' not specified in 'fleet_control'; assuming 'AcrossSexes'. NOTE: a two-sex fleet normalizing at a named 'Sel_norm_bin' previously used a per-sex reference -- set 'Sel_norm_scope' to 'WithinSex' to keep that behaviour.", default_msg_when = "sel_norm_scope_flip", tmb_target = "sel_norm_scope"),
    .rce_col("Comp_distribution", "fleet_control", "Composition data distribution:\r\n-1 = AFSC multinomial\r\n0 = full multinomial\r\n1 = dirichlet-multinomial", type = "switch", allowed = "comp_loglike_map", has_default = TRUE, default = "MultinomialAFSC", default_msg = "'Comp_distribution' not specified in 'fleet_control', assuming 'MultinomialAFSC'", aliases = "Comp_loglike", tmb_target = "comp_ll_type"),
    .rce_col("Comp_weights", "fleet_control", "Composition weight, on a scale set by 'Comp_distribution'. \r\nUnder a multinomial it is the natural-scale multiplier on the input sample size. \r\nUnder a Dirichlet-multinomial the model uses exp(Comp_weights), so the column is the LOG of the starting weight -- the usual template value of 1 is a starting weight of e, not 1; use 0 for a weight of 1. \r\nRead when a model is built from scratch -- a refit keeps the weight it is given. \r\nSee 'Comp_weights_mcallister' for the weight a fit implies, and reweight_comps() to tune towards it."),
    .rce_col("CAAL_distribution", "fleet_control", "Composition data distribution:\r\n-1 = AFSC multinomial\r\n0 = full multinomial\r\n1 = dirichlet-multinomial", type = "switch", allowed = "comp_loglike_map", has_default = TRUE, default = "Multinomial", default_msg = "'CAAL_distribution' not specified in 'fleet_control', assuming 'Multinomial'", default_msg_when = "has_caal", aliases = "CAAL_loglike", tmb_target = "caal_ll_type"),
    .rce_col("CAAL_weights", "fleet_control", "Conditional age-at-length composition weight, on a scale set by 'CAAL_distribution' (as for 'Comp_weights'). \r\nUnder a multinomial it is the natural-scale multiplier on the input sample size. \r\nUnder a Dirichlet-multinomial the model uses exp(CAAL_weights), so the column is the LOG of the starting weight -- the default of 1 is a starting weight of e, not 1. \r\nRead when a model is built from scratch -- a refit keeps the weight it is given.", has_default = TRUE, default = 1, default_msg = "'CAAL_weights' not specified in 'fleet_control', assuming 1", default_msg_when = "has_caal"),
    .rce_col("Comp_accum_young", "fleet_control", "Age/length composition young-tail accumulation bin (AFSC ac_yng): a 1-based ordinal on the fleet's composition dimension; bins below it are folded into it before the likelihood. NA or 1 = no young accumulation.", type = "integer", has_default = TRUE, default = NA, tmb_target = "comp_accum_young"),
    .rce_col("Comp_accum_old", "fleet_control", "Age/length composition old-tail accumulation bin (AFSC ac_old): a 1-based ordinal on the fleet's composition dimension; bins above it are folded into it before the likelihood. NA, 0, or a value >= the number of bins = no old accumulation.", type = "integer", has_default = TRUE, default = NA, tmb_target = "comp_accum_old"),
    .rce_col("Observation_units", "fleet_control", "1 = catch/index is weight (mt) \r\n2 = catch/index is in numbers (thousands of fish) \r\nThe model works in mt and thousands of fish throughout: numbers-at-age are thousands and weight-at-age is kg, so their product is mt.", type = "integer", aliases = c("Weight1_Numbers2", "weight1_Numbers2"), tmb_target = "flt_units"),
    .rce_col("Weight_index", "fleet_control", "Weight index to use for calculation of derived quantities", type = "integer", tmb_target = "flt_wt_index"),
    .rce_col("Age_transition_index", "fleet_control", "Age transition matrix (e.g. growth trajectory) index to used convert age to length", type = "integer", tmb_target = "flt_age_transition_index"),
    .rce_col("Catchability_index", "fleet_control", "Index used to give fleets the SAME catchability. Fleets sharing a value share one q parameter, so the group can carry only one answer to whether q is estimated: the LEAD fleet -- the group's first non-Off fleet -- decides for all of them, regardless of fleet type, and the others' Catchability settings are not used. A fleet with no index_data of its own is therefore still estimated if its group's lead is. Give a fleet its own value when it should be estimated independently.\r\nThe exception is 'Analytical' and 'AnalyticalArith', which solve catchability from each fleet's own index observations rather than from the shared parameter, so a group containing one does NOT share a catchability even when every fleet in it carries the same setting. 'Environmental' and 'AR1' do share: they rebuild q from the group's shared parameters, including when the fleets name different environmental series (the lead fleet's is used). If the lead is 'Fixed' the group shares nothing at all: no catchability is estimated and each fleet sits at its own 'Catchability_init'. Where a q IS estimated for the group, its STARTING value is the mean of the group's log 'Catchability_init' (TMB averages the initial values of parameters mapped together), not the lead's; the prior centre does use the lead's. data_check() reports the analytical case, a Fixed lead that leaves fleets on different inits, and a differing 'Catchability' or 'Time_varying_q' within a group.", type = "integer", aliases = "Q_index", tmb_target = "flt_q_lead"),
    .rce_col("Catchability", "fleet_control", "Catchability form. Accepts integer codes or readable strings:\r\n0 or \"Fixed\" = fixed at Catchability_init\r\n1 or \"Estimated\" = estimate as a free parameter\r\n2 or \"Estimated-with-prior\" = estimate with a normal prior N(Catchability_init, Catchability_prior_sd)\r\n3 or \"Analytical\" = geometric-mean analytical q following Ludwig and Walters 1994\r\n4 or \"PowerEquation\" = power equation (NOT YET IMPLEMENTED)\r\n5 or \"Environmental\" = linear equation log(q_y) = q_mu + beta * index_y; the environmental index is specified by Time_varying_q\r\n6 or \"AR1\" = REMOVED; data_check() errors. AR1 random deviates fit to an environmental index (sensu Rogers et al 2024; 10.1093/icesjms/fsae005), index specified by Time_varying_q -- but the deviates were never estimated, so q came back constant and the objective was not comparable with another model's. Express it as a q linkage with ar1(1 | Year) and 'observe', passed to fit_mod(qFun = ); the error gives the call.\r\n7 or \"AnalyticalArith\" = arithmetic-mean analytical q (AMAK/ebswp form, pair with the MVN survey likelihood)\r\nApplies to any fleet carrying index_data, a fishery with a CPUE series included; such a fleet's index uses that fleet's own selectivity. A fleet with NO fitted index rows gets no catchability whatever this says, since a q with no index to inform it is a flat direction -- unless it follows the lead of a shared Catchability_index group.", type = "switch", allowed = "q_map", aliases = "Estimate_q", tmb_target = "est_index_q"),
    .rce_col("Catchability_init", "fleet_control", "Starting value or fixed value for catchability. Must be positive on any fleet that carries index_data, whatever its Fleet_type -- it has no default, and it is logged to seed index_log_q, so a blank or zero gives a non-finite starting value. Not read under Analytical or AnalyticalArith, which solve q from the data.", aliases = c("Q_prior", "Q_init"), tmb_target = "index_log_q_prior"),
    .rce_col("Catchability_prior_sd", "fleet_control", "Standard deviation for the q prior. Must be positive under Estimated-with-prior, where the prior is scored at it, and under AR1, where the estimated sd starts from it.", aliases = "Q_sd_prior"),
    .rce_col("Time_varying_q", "fleet_control", "0 or \"Off\" = no\r\n1 or \"IID\" = penalized deviate or random effect\r\n2 or \"AR1\" = REMOVED in 5.16.0; data_check() errors on it. It was never an AR1 -- the template scored it with the same independent normal penalty as \"IID\", and index_q_rho belongs to the removed Catchability = \"AR1\" (QAR1) path, not to this switch. Use \"IID\" for the fit it actually gave, or express the autocorrelation as a q linkage: build_catchability(linkages = list(q = linkage_spec(~ ar1(1 | Year), by = ~ fleet))).\r\n3 or \"Block\" = time blocks with no penalty\r\n4 or \"RandomWalk\" = random walk from mean following Dorn 2018 (dnorm(q_y - q_y-1, 0, sigma)\r\nIf Catchability = 5, this determines the environmental index to be used in the equation log(q_y) = q_mu + beta * index_y\r\nIf \"random_q\" is selected in fit_mod, penalized deviates (1) and random walk parameters (4) will be treated as random effects.\r\nSoft-deprecated as a whole: the linkage grammar expresses the same deviations, with the deviation sd estimated or fixed.", type = "switch", allowed = "tv_q_map", tmb_target = "index_varying_q"),
    .rce_col("Time_varying_q_sd", "fleet_control", "Starting or fixed sd for the time-varying q deviations. Must be positive when Time_varying_q is IID, AR1 or RandomWalk, which penalize the deviations at it; Block needs none.", aliases = "Time_varying_q_sd_prior"),
    .rce_col("Index_distribution", "fleet_control", "Survey/index biomass observation likelihood family.\r\n0 or \"Lognormal\" (default) = independent lognormal on the log observation, with the bias correction.\r\n1 \"MVN\" / 2 \"MVNORM\" = multivariate normal on the natural-scale residual, with a user-supplied covariance in index_cov; they differ only by a constant.\r\n3 \"Normal\" = independent normal on the natural-scale residual with an ABSOLUTE sd from Log_sd (not a log-scale CV). Matches the AMAK avo_like/cpue_like term for term, so it is what the ADMB bridges compare against.\r\n4 \"TruncatedNormal\" = the same normal, left-truncated at zero. An index cannot be negative, so over the values the data can take the density is renormalized by log Phi(mu/sd). Prefer this to 3 unless an exact ADMB comparison is needed: it is the only natural-scale family sim_mod() can draw from exactly, since 3 has to reject the non-positive draws data_check() would refuse.", type = "switch", allowed = "index_distribution_map", meta = TRUE, has_default = TRUE, default = "Lognormal", aliases = "Index_loglike", tmb_target = "index_ll_type"),
    .rce_col("Estimate_index_sd", "fleet_control", "0 = use input \"Log_sd\" from index_data\r\n1 = estimate as free parameter\r\n2 = estimate analytically following Ludwig and Walters (1994)", type = "switch", allowed = "estimate_sd_map", aliases = "Estimate_survey_sd", tmb_target = "est_sigma_index"),
    .rce_col("Index_sd", "fleet_control", "Starting value to be used if \"Estimate_index_sd\" = 1", aliases = c("Survey_sd_prior", "Index_sd_prior")),
    .rce_col("Estimate_catch_sd", "fleet_control", "0 = use input \"Log_sd\" from catch_data\r\n1 = estimate as free parameter\r\n2 = estimate analytically following Ludwig and Walters (1994)", type = "switch", allowed = "estimate_sd_map", tmb_target = "est_sigma_fsh"),
    .rce_col("Catch_sd", "fleet_control", "Starting value to be used if Estimate_catch_sd = 1", aliases = "Catch_sd_prior"),
    .rce_col("Proj_F_proportion", "fleet_control", "The proportion of future fishing mortality assigned to this fleet", aliases = "proj_F_prop"),

    # ---- Orphans: documented historically but read nowhere in the model ----
    .rce_col("Catch_units", "fleet_control", "Units used for survey: 1 = kg; 2 = numbers", meta = FALSE, status = "orphan"),
    .rce_col("Sex", "fleet_control", "INERT -- read nowhere in the model, so setting it has no effect. Sex is set per observation on comp_data Sex (0 = combined; 1 = female only; 2 = male only; 3 = joint female and male), not per fleet. Retained only so an older workbook still reads.", meta = FALSE, status = "orphan"),

    # ======================================================================
    # bioenergetics_control sheet, in write order
    # ======================================================================
    .rce_col("Ceq", "bioenergetics_control", "Integer: switch for which bioenergetics equation to use for each species for ft to scale max consumption: \r\n1 = Exponential (Stewart et al 1983)\r\n2 = Temperature-dependence for warm-water species (Kitchell et al 1977; sensu Holsman et al 2015)\r\n3 = temperature dependence for cool and cold-water species (Thornton and Lessem 1979)\r\n4 = for direct input of consumption in Pyrs  where consumption at age = Numbers * Pyrs (CA set to 1, fday set to 1, CB set to 0)", type = "integer", has_default = TRUE, default = 1L, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Cindex", "bioenergetics_control", "Integer: which environmental index in env_data to use to drive bioenergetics", type = "integer", has_default = TRUE, default = 0L, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Pvalue", "bioenergetics_control", "Numeric: this scales the maximum consumption used for ration for each species; Pvalue is in Cmax*fT*Pvalue*Pyrs", has_default = TRUE, default = 1, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("fday", "bioenergetics_control", "Numeric: number of foraging days per year for each species", has_default = TRUE, default = 365, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CA", "bioenergetics_control", "Intercept of allometric mass function for calculating maximum consumption: CA * Weight ^ CB", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CB", "bioenergetics_control", "Slope of allometric mass function for calculating maximum consumption: CA * Weight ^ CB", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Qc", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Tco", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Tcm", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("Tcl", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CK1", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    .rce_col("CK4", "bioenergetics_control", "Parameter for temperature scaling function of maximum consumption specified by Ceq", has_default = TRUE, default = 0, default_scope = "single-species mode (msmMode == 0), per-species"),
    # Per-predator-species vectors defaulted by switch_check
    # (rep(0, nspp) / rep(1, nspp)); their defaulting stays imperative there.
    .rce_col("Diet_distribution", "bioenergetics_control", "Diet composition likelihood distribution per predator species:\r\n0 = multinomial\r\n1 = dirichlet-multinomial", type = "switch", allowed = "diet_loglike_map", meta = TRUE, aliases = "Diet_loglike", tmb_target = "diet_ll_type"),
    .rce_col("Diet_comp_weights", "bioenergetics_control", "Diet composition weight per predator species, on a scale set by 'Diet_distribution' (as for 'Comp_weights'). \r\nUnder a multinomial it is the natural-scale multiplier on the input sample size. \r\nUnder a Dirichlet-multinomial the model uses exp(Diet_comp_weights), so the column is the LOG of the starting weight. \r\nRead when a model is built from scratch -- a refit keeps the weight it is given.", meta = TRUE)
  )

  names(rows) <- vapply(rows, function(r) r$name, character(1))
  rows
}

# -----------------------------------------------------------------------------
# Accessors over the schema
# -----------------------------------------------------------------------------

#' Apply a column's schema default when the value is absent.
#'
#' Reproduces `switch_check()`'s local `set_default(val, default, msg)`: when
#' `val` is NULL, emit the schema's `default_msg` (gated by `default_msg_when`)
#' and return the schema `default`; otherwise return `val` unchanged. Sourcing
#' the value and message from the schema is what removes the hand-copied
#' defaults from `switch_check()`.
#'
#' @param val The current column value (NULL if the column is absent).
#' @param col Canonical column name (schema key).
#' @param schema A prefetched `.rce_column_schema()` (avoids rebuilding it per
#'   call).
#' @param np_hake Value of the non-parametric/Hake/LogisticPM predicate, for
#'   columns whose message only fires when such a fleet is present
#'   (`default_msg_when == "np_hake"`).
#' @keywords internal
#' @noRd
.rce_apply_default <- function(val, col, schema = .rce_column_schema(),
                               np_hake = FALSE, conditions = list()) {
  if (!is.null(val)) return(val)
  row <- schema[[col]]
  if (is.null(row) || !isTRUE(row$has_default))
    stop("Internal: no schema default for column '", col, "'")
  msg  <- row$default_msg
  # A gated default message fires only when its condition holds -- so we don't
  # nag about an optional input the current model configuration never uses (e.g.
  # a CAAL distribution for a model with no CAAL data). The gate is named in the
  # schema's `default_msg_when`; `np_hake` is the legacy first-class gate, every
  # other named gate is supplied in `conditions` (a named logical list computed by
  # switch_check()). An ungated message (no `default_msg_when`) always fires.
  gate <- row$default_msg_when
  if (!is.null(gate) && nzchar(gate)) {
    on <- if (identical(gate, "np_hake")) isTRUE(np_hake) else isTRUE(conditions[[gate]])
    if (!on) msg <- NULL
  }
  if (!is.null(msg)) message(msg)
  row$default
}

#' Upgrade deprecated fleet_control column names to canonical, in place.
#'
#' The single migration point for legacy fleet_control column names: every
#' canonical column carries its historical spellings in the schema `aliases`
#' field, and this walks them, renaming any present old name to the canonical
#' one. Both `read_data()` (on the xlsx path) and `switch_check()` (on every
#' fit path) call it, so a data list built either way is upgraded identically
#' from the one schema.
#'
#' Double-fire-safe: a no-op when the old name is absent (so re-running on an
#' already-upgraded list is silent), and it never clobbers an existing
#' canonical column. Emits one deprecation message per rename actually applied.
#'
#' @param fc A `fleet_control` data frame (or NULL).
#' @return `fc` with any deprecated column names upgraded to canonical.
#' @keywords internal
#' @noRd
.rce_upgrade_fleet_control_aliases <- function(fc) {
  if (is.null(fc)) return(fc)
  schema <- .rce_column_schema()
  for (row in schema) {
    if (row$sheet != "fleet_control" || length(row$aliases) == 0L) next
    for (old in row$aliases) {
      if (!is.null(fc[[old]])) {
        if (is.null(fc[[row$name]])) fc[[row$name]] <- fc[[old]]
        fc[[old]] <- NULL
        message(sprintf("'%s' is deprecated; use '%s'.", old, row$name))
      }
    }
  }
  fc
}

#' Upgrade deprecated data_list-level (control / bioenergetics) names to canonical.
#'
#' The analogue of `.rce_upgrade_fleet_control_aliases()` for the top-level
#' data_list elements that are NOT fleet_control columns -- the control scalars
#' and bioenergetics per-species vectors, whose deprecated names live in the
#' same schema `aliases` field (e.g. `sigma_rec_prior` -> `sigma_rec`,
#' `Diet_loglike` -> `Diet_distribution`). Double-fire-safe; one message per
#' rename applied.
#'
#' @param data_list An Rceattle data list (or NULL).
#' @return `data_list` with any deprecated control/bioenergetics element names
#'   upgraded to canonical.
#' @keywords internal
#' @noRd
.rce_upgrade_data_list_aliases <- function(data_list) {
  if (is.null(data_list)) return(data_list)
  schema <- .rce_column_schema()
  for (row in schema) {
    if (row$sheet == "fleet_control" || length(row$aliases) == 0L) next
    for (old in row$aliases) {
      if (!is.null(data_list[[old]])) {
        if (is.null(data_list[[row$name]])) data_list[[row$name]] <- data_list[[old]]
        data_list[[old]] <- NULL
        message(sprintf("'%s' is deprecated; use '%s'.", old, row$name))
      }
    }
  }
  data_list
}

#' Rows for one sheet, in schema (write) order.
#' @keywords internal
#' @noRd
.rce_schema_rows <- function(sheet, include_orphans = FALSE) {
  rows <- .rce_column_schema()
  rows <- Filter(function(r) r$sheet == sheet, rows)
  if (!include_orphans) rows <- Filter(function(r) r$status != "orphan", rows)
  rows
}

#' Canonical column/scalar names for one sheet, in write order.
#' @keywords internal
#' @noRd
.rce_schema_names <- function(sheet, include_orphans = FALSE) {
  unname(vapply(.rce_schema_rows(sheet, include_orphans),
                function(r) r$name, character(1)))
}

# -----------------------------------------------------------------------------
# meta_data sheet generator (the embedded workbook dictionary)
# -----------------------------------------------------------------------------
#
# The meta_data sheet is a 3-column [Sheet name | Column/row name | Description]
# frame documenting every control scalar, fleet_control column, and
# bioenergetics scalar, with a per-sheet header row for the remaining data
# sheets and a block of free-text NOTE rows at the end. This generator emits the
# schema-driven rows; the sheet-header + NOTE footer is a static template.

# Per-sheet header rows (Column/row name is NA, Description names the sheet).
.RCE_META_SHEET_HEADERS <- list(
  c("fleet_control",   "Survey and fishery data specifications"),
  c("index_data",      "Survey index or fishery indices in weight (mt) or numbers (thousands of fish)."),
  c("catch_data",      "Total catch in weight (mt) or numbers data"),
  c("comp_data",       "Survey/fishery age or length composition data. Note if sex is 3, put female composition data then male composition data (similar to SS)."),
  c("caal_data",       "Survey/fishery CAAL data. Note if sex is 3, put female CAAL data then male CAAL data (similar to SS)."),
  c("emp_sel",         "Empirical/fixed selectivity for surveys and fisheries (leave empty if not used)"),
  c("age_trans_matrix","Age transition matrix (e.g. growth trajectory) used to convert age to length for length comp data. \r\nCan have multiple matrices for a species specified by Age_transition_index."),
  c("age_error",       "Aging error matrices. Can have only one per species."),
  c("weight",          "Time-invariant or -varying empirical weight-at-age for calculation of derived quantities (SSB, Consumption/Ration, Suitability, Total Catch, Survey Biomass, etc). \r\nCan have multiple weight-at-age data-sets for each species."),
  c("maturity",        "Maturity-at-age for each species"),
  c("sex_ratio",       "Percent female at age for each species"),
  c("M1_base",         "Residual natural mortality for each species")
)

# env_data / ration_data / diet_data headers sit after the bioenergetics block.
.RCE_META_SHEET_HEADERS_TAIL <- list(
  c("env_data",    "Environmental indices such as bottom temperature data to incorporate into ration equation specified by Ceq and Cindex. Also used to drive catchability if Catchability = 5 or 6. Will use the mean for missing years. Temperature should be in Celsius."),
  c("ration_data", "Annual relative foraging rate by age. Multiplied by pvalue and fday to scale maximum consumption to the number of days in a year that foraging occurs."),
  c("diet_data",   "Stomach proportion by weight for each predator, prey, predator age, prey age combination. Multiple diet-data formats can be included:\r\n\r\n1) If Pred_age >= 0 and Prey_age >= 0, data is assumed to be  diet proportion of prey-at-age/sex in predator-at-age/sex. \r\n2) If Pred_age >= 0 and Prey_age < 0, data is assumed to be mean diet proportion of prey-spp in predator-at-age/sex (sum across prey ages and sexes)\r\n3) If Pred_age < 0 and Prey_age < 0, data is assumed to be  mean diet proportion of prey-spp in predator-spp (sum across prey ages/sexes and take mean across predator ages/sexes)\r\n4) If Pred_age < -500 and Prey_age < 0, data is assumed to be weighted mean diet proportion of prey-spp in predator-spp (sum across prey ages/sexes and take weighted mean across predator ages/sexes). Weights are estimated predators-at-age. \r\n\r\nIf \"Year = 0\", the diet will be assumed to be the average between \"suit_styr\" and \"suit_endyr\". \r\n\r\nOnly diet-data type 1 can be used for MSVPA based suitability")
)

# Free-text NOTE / legend rows carried verbatim as the sheet footer.
.RCE_META_NOTES <- c(
  "NOTE: Most objects are ordered by species code if not specified",
  "NOTE: Lengths are index 1 through nlengths",
  "NOTE: Columns for ages are index by 1 through nages, but are placeholders.",
  "NOTE: For catch, index, and comp data, if \"Year\" is negative, it will predict for that year, but not include the data in the likelihood.",
  "NOTE: For emp_sel, weight, and ration_data, if \"Year\" == 0, those data will be used for all years"
)

#' Build the `meta_data` documentation sheet from the schema.
#'
#' Emits the control-scalar rows, the fleet_control header + column rows, the
#' data-sheet header rows, the bioenergetics-scalar rows, and the tail sheet
#' headers + NOTE footer -- reproducing the layout of the bundled
#' `meta_data_names.xlsx`.
#'
#' @return A data.frame with columns `Sheet name`, `Column/row name`,
#'   `Description`.
#' @keywords internal
#' @noRd
.rce_build_meta_data_df <- function() {
  add <- function(acc, sheet, col, desc) {
    rbind(acc, data.frame(`Sheet name` = sheet, `Column/row name` = col,
                          Description = desc, check.names = FALSE,
                          stringsAsFactors = FALSE))
  }
  out <- data.frame(`Sheet name` = character(0), `Column/row name` = character(0),
                    Description = character(0), check.names = FALSE,
                    stringsAsFactors = FALSE)

  # Control scalars (Sheet name "Control")
  for (r in .rce_schema_rows("control"))
    if (isTRUE(r$meta)) out <- add(out, "Control", r$name, r$doc)

  # fleet_control header + columns
  out <- add(out, "fleet_control", NA_character_, .RCE_META_SHEET_HEADERS[[1]][2])
  for (r in .rce_schema_rows("fleet_control"))
    if (isTRUE(r$meta)) out <- add(out, "fleet_control", r$name, r$doc)

  # Data-sheet headers (index_data .. M1_base)
  for (h in .RCE_META_SHEET_HEADERS[-1]) out <- add(out, h[1], NA_character_, h[2])

  # bioenergetics scalars
  for (r in .rce_schema_rows("bioenergetics_control"))
    if (isTRUE(r$meta)) out <- add(out, "bioenergetics_control", r$name, r$doc)

  # Tail sheet headers
  for (h in .RCE_META_SHEET_HEADERS_TAIL) out <- add(out, h[1], NA_character_, h[2])

  # NOTE footer (carried in the Sheet name column, as in the bundled file)
  for (n in .RCE_META_NOTES) out <- add(out, n, NA_character_, NA_character_)

  out
}


#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Model-level switches
#
# The switches that configure the MODEL rather than a workbook column:
# msmMode, estimateMode, initMode and the rest. They live in maps in
# R/0-switches.R and the R/0-build_*.R constructors, are defaulted in
# switch_check(), and are documented in fit_mod() and the build_*()
# constructors -- with no one place saying what the full set is.
#
# A SECOND table rather than rows in .rce_column_schema(): these are not
# workbook columns, and write_data(), read_data(), the meta sheet and the
# R/data.R drift guard all iterate that list. Adding non-columns to it would
# put them in the workbook.
#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#

#' One model-level switch
#'
#' @param name Canonical name, as `fit_mod()` or a `build_*()` takes it.
#' @param doc One sentence: what it selects.
#' @param allowed Name of the map defining its values, in the package namespace.
#' @param default The value applied when the user supplies none.
#' @param scope `"scalar"`, `"per-species"`, or `"per-fleet"` -- whether one
#'   value configures the model or one value per species/fleet is expected.
#' @param tmb_target The `DATA_*` object it reaches, where it reaches one.
#' @param set_by The function that takes it.
#' @keywords internal
#' @noRd
.rce_switch <- function(name, doc, allowed = NA_character_, default = NA,
                        scope = "scalar", tmb_target = NA_character_,
                        set_by = "fit_mod") {
  list(name = name, doc = doc, allowed = allowed, default = default,
       scope = scope, tmb_target = tmb_target, set_by = set_by)
}

#' The model-level switches
#'
#' @description
#' Companion to [.rce_column_schema()], for the switches that are not workbook
#' columns. `.rce_config_schema()` projects from this, so the comments
#' `save_config()` writes list every valid value rather than a hand-kept subset;
#' `test-schema-cpp-dispatch.R` checks the ones that reach the template against
#' the `case` labels that consume them.
#'
#' @return A named list of switch definitions, keyed by canonical name.
#' @keywords internal
#' @noRd
.rce_model_switch_schema <- function() {
  rows <- list(
    .rce_switch("msmMode",
      "Predation-mortality mode: single-species, Holsman et al. (2015) MSVPA (Type II), or Holling Type III MSVPA.",
      allowed = "msmMode_map", default = 0L, tmb_target = "msmMode"),
    .rce_switch("estimateMode",
      "What the fit does: hindcast, projection, or a build-only debug pass.",
      allowed = "estimateMode_map", default = 0L),
    .rce_switch("initMode",
      "How the initial age structure is derived. See ?fit_mod.",
      allowed = "initMode_map", default = 2L, tmb_target = "initMode"),
    .rce_switch("suitMode",
      "How predator-prey suitability is derived, per predator.",
      allowed = "suitMode_map", default = 0L, scope = "per-species",
      tmb_target = "suitMode"),
    .rce_switch("avgnMode",
      "Average abundance-at-age approximation in the predation equations. Only mode 0 is implemented; the alternatives are declared and have no effect.",
      default = 0L),
    .rce_switch("HCR",
      "Harvest control rule applied in the projection.",
      allowed = "hcr_map", default = 0L, set_by = "build_hcr"),
    .rce_switch("srr_fun",
      "Stock-recruit form fitted to the hindcast.",
      allowed = ".SRR_FUNS", default = 0L,
      tmb_target = "srr_fun", set_by = "build_srr"),
    .rce_switch("srr_pred_fun",
      "Stock-recruit form used to predict recruitment in the projection.",
      allowed = ".SRR_FUNS", default = 0L,
      tmb_target = "srr_pred_fun", set_by = "build_srr"),
    .rce_switch("srr_est_mode",
      "Whether the stock-recruit parameters are fixed, estimated, or given a prior.",
      allowed = "srr_est_mode_map", default = 1L, tmb_target = "srr_est_mode",
      set_by = "build_srr"),
    .rce_switch("M1_model",
      "Residual natural mortality: fixed, or estimated at which resolution.",
      allowed = ".M1_MODELS", default = 0L, scope = "per-species",
      set_by = "build_M1"),
    .rce_switch("growth_model",
      "Growth curve: empirical weight-at-age, or which parametric form.",
      allowed = ".GROWTH_FUN_TO_INT", default = 0L, scope = "per-species",
      tmb_target = "growth_model", set_by = "build_growth"),
    .rce_switch("estDynamics",
      "Whether population dynamics are estimated, or numbers-at-age supplied.",
      allowed = "estDynamics_map", default = 0L, scope = "per-species",
      tmb_target = "estDynamics")
  )
  stats::setNames(rows, vapply(rows, function(r) r$name, character(1)))
}

#' Names of the model-level switches
#' @keywords internal
#' @noRd
.rce_model_switch_names <- function() names(.rce_model_switch_schema())
